"""Content of the ULMs SDS — text only, no formatting decisions.

Structured to the outline the course requires (Week 09 - System Design
Specification, slides 29-33): 1 General Product Description, 2 System
Requirement, 3 System Specification, 4 System Analysis and Design,
5 System Decomposition, 6 Data Store, 7 Security, 8 Authorization,
9 System Recovery, 10 Installation and Deployment, 11 Back-out.

v1.3 — facts re-read from front-end-branch on 25 Sep 2569 (after v1.2 at 0cb21a7, 17 Sep): schema.prisma,
backend/src, frontend/src, .github/workflows/ci.yml. Where the design is agreed
but not built yet, the status column says so rather than the text implying
otherwise.

Style follows the hand-edited v1.0 the team submitted on 3 Sep (see
docs/build/ULMs-SDS-v1.0.docx): no "·" separators, no reviewer summary page,
no glossary/references/traceability sections, few explanatory notes, and
multi-step paths written one step per line. Keep to that when editing.

Block grammar is the one doc_builder.py understands:
    ("h1", ...) ("h2", ...) ("p", ...) ("note", ...)
    ("bullets", [items]) ("code", [lines])
    ("table", [widths in cm], [header], [[row], ...])   "\\n" in a cell = line break
    ("image", "figures/x.png", width in cm, "caption")
    ("wide_image", "figures/x.png", "caption")
"""

VERSION = "1.3"
DOC_TITLE = "ULMs System Design Specification v1.3"
RUNNING_HEADER = "ULMs SDS v1.3"
OUTPUT_STEM = "ULMs-SDS-v1.3"
GENERATOR = "gen_sds_docx.py"
SOURCE_FILE = "sds_data.py"

# v1.0 was submitted with body paragraphs indented by hand; do it properly here.
PARAGRAPH_INDENT_CM = 1.0

COVER = {
    "kicker": "System Design Specification",
    "acronym": "SDS",
    "title_th": "ระบบบริหารจัดการการยืม-คืนอุปกรณ์มหาวิทยาลัย",
    "title_en": "University Equipment Lending Management System (ULMs)",
    "version": "Version 1.3",
    "date": "25 กันยายน 2569",
    "team": 'ทีม: "miro ปั่น 14 บาท"',
    "course": "รหัสวิชา 01204341 Software Engineering",
    "faculty": "ภาควิชาวิศวกรรมคอมพิวเตอร์ คณะวิศวกรรมศาสตร์",
    "university": "มหาวิทยาลัยเกษตรศาสตร์",
}

TOC_TITLE = "สารบัญ"

BODY = [
    ('h1', '1. General Product Description'),
    ('h2', '1.1 Purpose'),
    ('p',
     'เอกสารฉบับนี้แปลงความต้องการใน ULMs SRS ให้เป็นการออกแบบที่ลงมือสร้างได้จริง โดยระบุยูสเคส ผังกระบวนการ สถาปัตยกรรม โครงสร้างฐานข้อมูล รายการฟังก์ชันของระบบ การควบคุมสิทธิ์ และขั้นตอนการนำระบบขึ้นใช้งาน เพื่อให้ผู้พัฒนาทุกคนเห็นภาพเดียวกันและสร้างงานที่ประกอบเข้าด้วยกันได้ ทั้งยังใช้เป็นเกณฑ์อ้างอิงในการรีวิวโค้ดและออกแบบกรณีทดสอบ'),
    ('h2', '1.2 System Scope'),
    ('p',
     'ULMs เป็นเว็บแอปพลิเคชันสำหรับบริหารจัดการการยืม-คืนอุปกรณ์และสถานที่ของมหาวิทยาลัยเกษตรศาสตร์ รองรับผู้ใช้ 4 บทบาท ครอบคลุมตั้งแต่ค้นหาอุปกรณ์ ส่งคำขอยืม อนุมัติ จ่ายของ รับคืน ประเมินความเสียหาย จนถึงการจัดการเครดิตและการอุทธรณ์'),
    ('table', [5.0, 11.2],
     ['อยู่ในขอบเขต', 'ไม่อยู่ในขอบเขต'],
     [
        ['บัญชีอุปกรณ์รายชิ้นและสถานที่ สิทธิ์การเข้าใช้ตามหน่วยงาน', 'การจัดซื้ออุปกรณ์ใหม่และการเบิกจ่ายงบประมาณ'],
        ['วงจรยืม-คืนเต็มรูปแบบ พร้อมหลักฐานภาพถ่าย', 'ระบบบัญชีการเงินและการเรียกเก็บค่าเสียหายเป็นตัวเงิน'],
        ['ระบบเครดิต บทลงโทษ และการอุทธรณ์', 'การเชื่อมต่อกับระบบทะเบียนนักศึกษาโดยตรง'],
    ]),
    ('h2', '1.3 การเปลี่ยนแปลงจากฉบับ 1.2'),
    ('table', [4.6, 11.6],
     ['หัวข้อ', 'สิ่งที่เปลี่ยน'],
     [
        ['2.2 และภาคผนวก ก', 'ยูสเคสทุกตัวมีของจริงรองรับแล้ว รวมการจองห้อง การอุทธรณ์ การแจ้งเตือนทางอีเมล และการส่งออกรายงาน'],
        ['2.3 และ 3.4', 'กำหนดมารับเป็น 1 วันนับจากเวลาเริ่มยืมตาม SRS v1.1 เวลาปิดทำการตั้งได้ ค่าเริ่มต้น 08:00-17:00 และเจ้าหน้าที่ได้รับแจ้งเมื่อมีงาน'],
        ['2.3.2', 'การต่ออายุของผู้ที่เครดิต D2-D3 ส่งอาจารย์แล้ว ตรง FR-RNW-06'],
        ['4.2.2', 'ฟังก์ชันเพิ่มเป็น 111 รายการใน 11 โดเมน งานตามเวลาเหลือ 6 งานและทำงานได้ทั้งหมด รหัสเชิงธุรกิจ 104 ตัว มีคำแปลไทย 103 ตัว'],
        ['4.4', 'ตารางเพิ่มเป็น 35 migration 28 ชุด ตัด setUserBan ออกแล้ว work_time เก็บในตาราง SystemSetting'],
        ['2.3.2 และ 4.4.3', 'อาจารย์เห็นรายงานตรวจสภาพของเจ้าหน้าที่ในหน้าอุทธรณ์ และปรับระดับความเสียหายลงได้ ระบบคิดบทลงโทษใหม่แบบเดียวกับตอนตรวจ และเก็บระดับที่ปรับใน AppealInfo.RevisedCondition (FR-APL-03, FR-APL-06)'],
        ['5.3', 'หน้าเว็บใช้ชนิดข้อมูลที่สร้างจากเราเตอร์จริง CI ตรวจว่าไม่ล้าสมัย ความต่างของสองฝั่งเหลือศูนย์'],
        ['6, 8 และ 10', 'บริการสำรองข้อมูลจริง รูปหลักฐานเปิดได้ผ่านลิงก์ที่เซ็นและหมดอายุ การนำขึ้นใช้งานด้วย Docker Compose ตัวแปรสภาพแวดล้อมใหม่ และชุดทดสอบที่นับใหม่'],
    ]),
    ('h1', '2. System Requirement'),
    ('h2', '2.1 Purpose'),
    ('p',
     'หัวข้อนี้สรุปความต้องการที่การออกแบบต้องตอบ โดยยกมาจาก SRS ทุกข้อมีรหัสที่อ้างถึงได้ตรงจากตารางในหัวข้อถัดไป'),
    ('h2', '2.2 Use Case Model'),
    ('p',
     'ยูสเคสทั้งหมดของระบบ จัดกลุ่มตามผู้กระทำหลัก คอลัมน์สุดท้ายผูกกลับไปยังความต้องการใน SRS และคอลัมน์สถานะบอกว่ายูสเคสนั้นมีของจริงรองรับแล้วหรือยัง'),
    ('table', [1.8, 4.6, 2.8, 3.0, 4.0],
     ['รหัส', 'ยูสเคส', 'ผู้กระทำหลัก', 'ข้อกำหนด', 'สถานะ'],
     [
        ['UC-01', 'เข้าสู่ระบบและออกจากระบบ', 'ผู้ใช้ทุกบทบาท', 'FR-AUTH-01 ถึง 07', 'ใช้งานได้จริง'],
        ['UC-02', 'ค้นหาและดูรายละเอียดอุปกรณ์', 'ผู้ยืม', 'FR-BRW-01 ถึง 05', 'ใช้งานได้จริง'],
        ['UC-03', 'ส่งคำขอยืม', 'ผู้ยืม', 'FR-REQ-01 ถึง 10', 'ใช้งานได้จริง'],
        ['UC-04', 'อนุมัติหรือปฏิเสธคำขอ', 'อาจารย์', 'FR-APV-01 ถึง 06', 'ใช้งานได้จริง'],
        ['UC-05', 'จัดเตรียมและจ่ายอุปกรณ์', 'เจ้าหน้าที่, ผู้ยืม', 'FR-PKP-01 ถึง 05', 'ใช้งานได้จริง'],
        ['UC-06', 'ต่ออายุการยืม', 'ผู้ยืม, เจ้าหน้าที่, อาจารย์', 'FR-RNW-01 ถึง 06', 'ใช้งานได้จริง'],
        ['UC-07', 'คืนอุปกรณ์และตรวจสภาพ', 'ผู้ยืม, เจ้าหน้าที่', 'FR-RTN-01 ถึง 07', 'ใช้งานได้จริง'],
        ['UC-08', 'อุทธรณ์ผลการประเมิน', 'ผู้ยืม, อาจารย์', 'FR-APL-01 ถึง 06', 'ใช้งานได้จริง'],
        ['UC-09', 'ดูคะแนนเครดิตและประวัติการถูกหัก', 'ผู้ยืม', 'FR-CRD-01 ถึง 08', 'ใช้งานได้จริง'],
        ['UC-10', 'จองล่วงหน้า', 'ผู้ยืม', 'FR-RSV-01 ถึง 06', 'ใช้งานได้จริง'],
        ['UC-11', 'รับการแจ้งเตือน', 'ผู้ใช้ทุกบทบาท', 'FR-NTF-01 ถึง 06', 'ใช้งานได้จริง ทั้งในระบบและอีเมล'],
        ['UC-12', 'จัดการบัญชีอุปกรณ์และสถานที่', 'เจ้าหน้าที่', 'FR-EQP-01 ถึง 08', 'ใช้งานได้จริง'],
        ['UC-13', 'จัดการผู้ใช้และบทบาท', 'ผู้ดูแลระบบ', 'FR-ADM-01 ถึง 03', 'ใช้งานได้จริง รวมประวัติการยืมของผู้ใช้'],
        ['UC-14', 'ตั้งค่าพารามิเตอร์ของระบบ', 'ผู้ดูแลระบบ', 'FR-ADM-04', 'ใช้งานได้จริง เวลาทำการตั้งได้ ค่าเชิงเทคนิคอ่านได้อย่างเดียว'],
        ['UC-15', 'ตรวจสอบ Audit Log และดูรายงาน', 'ผู้ดูแลระบบ', 'FR-ADM-05, 06', 'ใช้งานได้จริง รวมสถิติความเสียหาย การใช้ห้อง และการส่งออก'],
    ]),
    ('h2', '2.3 Activity Model'),
    ('h2', '2.3.1 Activity State'),
    ('p',
     'สถานะทั้งหมดของระบบเก็บเป็นชนิดข้อมูลแบบ enum ในฐานข้อมูล'),
    ('table', [4.0, 5.0, 7.2],
     ['ชุดสถานะ', 'ค่าที่เป็นไปได้', 'ใช้กับอะไร'],
     [
        ['ApproveStatus', 'Pending, Approved, Rejected, Canceled', 'คำขอยืม การจอง และคำขอต่ออายุ'],
        ['CurrentStatus', 'Pending, Prepared, Lended, Returned, Inspected', 'วงจรชีวิตของการถือครองหนึ่งครั้ง (UsageLog)'],
        ['ResourceStatus', 'InStorage, Lended, Missing, Retired', 'สถานะของสิ่งที่ยืมได้แต่ละชิ้น Retired คือปลดระวางแล้ว'],
        ['ConditionType', 'Normal, MinorDamage, MajorDamage, Broken, Missing', 'ผลการตรวจสภาพและสภาพปัจจุบันของทรัพยากร'],
        ['PenaltyReason', 'DamagedItem, BrokenItem, LostItem, DidntReturn, ReturnLate', 'สาเหตุของการหักเครดิต'],
        ['NotificationType', 'RequestApproved, RequestRejected, PickupReminder, DueSoon, Overdue, CreditDeducted, AppealResult, RetirementRequested, RetirementDecided, SupervisorApprovalNeeded, AppealFiled, StaffTask', 'ชนิดของการแจ้งเตือนในระบบ DueSoon ส่งอีเมลด้วย StaffTask แจ้งเจ้าหน้าที่'],
    ]),
    ('p',
     'การเปลี่ยนสถานะของการยืมหนึ่งครั้ง เรียงตามลำดับที่เกิดขึ้นจริง'),
    ('table', [3.4, 3.4, 3.2, 6.2],
     ['จากสถานะ', 'ไปสถานะ', 'ใครสั่ง', 'เงื่อนไข'],
     [
        ['(ยังไม่มีแถว)', 'Pending', 'ผู้ยืม', 'ส่งคำขอผ่านการตรวจสิทธิ์ เครดิต และของคงเหลือแล้ว'],
        ['Pending', 'Approved', 'ระบบ หรือ อาจารย์', 'T0 และ T1 ของผู้ที่เครดิตดีอนุมัติอัตโนมัติ นอกนั้นอาจารย์ตัดสิน'],
        ['Pending', 'Rejected', 'อาจารย์', 'ต้องระบุเหตุผลประกอบ'],
        ['Pending / Approved', 'Canceled', 'ผู้ยืม หรือ ระบบ', 'ผู้ยืมยกเลิกเองก่อนเจ้าหน้าที่จัดเตรียม หรือไม่มารับภายใน 1 วันนับจากเวลาเริ่มยืม ถ้าจัดเตรียมไว้แล้วระบบก็ปล่อยของกลับคลังเช่นกัน'],
        ['Approved', 'Prepared', 'เจ้าหน้าที่', 'เลือกชิ้นจริงและจัดเตรียมเสร็จ'],
        ['Prepared', 'Lended', 'ผู้ยืม', 'ตรวจ Serial Number และอัปโหลดรูปตอนรับแล้ว'],
        ['Lended', 'Lended (เลื่อนกำหนด)', 'ระบบ เจ้าหน้าที่ หรือ อาจารย์', 'คำขอต่ออายุได้รับอนุมัติตามเส้นทางในหัวข้อ 2.3.2'],
        ['Lended', 'Returned', 'ผู้ยืม', 'แจ้งคืนพร้อมรูปตอนคืน'],
        ['Returned', 'Inspected', 'เจ้าหน้าที่', 'บันทึกผลตรวจสภาพ สำหรับ T2 ผู้ตรวจต้องไม่ใช่ผู้จัดเตรียม'],
        ['Lended', '(แจ้งของหาย)', 'เจ้าหน้าที่ หรือ ระบบ', 'ไม่คืนภายใน 2 สัปดาห์หลังกำหนด'],
    ]),
    ('h2', '2.3.2 Activity Diagrams'),
    ('p',
     'ผังกระบวนการทั้งสี่ แต่ละแถวคือหนึ่งบทบาท ใต้ผังมีตารางขั้นตอนกำกับ'),
    ('wide_image', 'figures/01-borrow.png',
     'ผังกระบวนการยืม'),
    ('table', [1.2, 2.4, 8.2, 4.2],
     ['ขั้น', 'ผู้ทำ', 'สิ่งที่ระบบทำ', 'ข้อกำหนด'],
     [
        ['1', 'ผู้ยืม', 'เลือกอุปกรณ์เข้าตะกร้า ระบุวันรับ–คืน แล้วส่งคำขอ ระบบตรวจสิทธิ์การเข้าใช้จากตาราง Eligibility และตรวจว่าระยะเวลาไม่เกินข้อกำหนด (กฎการยืม และระดับเครดิต)', 'FR-BRW-01 FR-REQ-01 FR-REQ-02'],
        ['2', 'ระบบ', 'ตรวจคะแนนเครดิตและของคงเหลือ ก่อนรับคำขอ ระดับเครดิตเป็นตัวกำหนดจำนวนวันที่ยืมได้และผู้มีสิทธิ์อนุมัติ แผนไม่มีการระงับสิทธิ์การยืม บทลงโทษมีผลผ่านระดับเครดิตเท่านั้น', 'FR-REQ-03'],
        ['3', 'ระบบ', 'เลือกเส้นทางอนุมัติ: T0 อนุมัติทันที T1 อนุมัติทันทีเมื่อเครดิตอยู่ D0-D1 T2 ส่งอาจารย์เสมอ', 'FR-REQ-04 ถึง 06'],
        ['4', 'อาจารย์', 'อนุมัติหรือปฏิเสธเป็นรายชิ้นภายในคำขอเดียว พร้อมเหตุผลเมื่อปฏิเสธ', 'FR-APV-02 FR-APV-03'],
        ['5', 'ระบบ', 'ตั้งกำหนดมารับภายใน 1 วันนับจากเวลาเริ่มยืม แจ้งเตือนผู้ยืม และแจ้งเจ้าหน้าที่ของหน่วยงานว่ามีของต้องเตรียม ถ้าไม่มารับตามกำหนด ยกเลิกและปล่อยของกลับคลังอัตโนมัติ', 'FR-APV-05 FR-APV-06 FR-PKP-05 FR-NTF-03'],
        ['6', 'เจ้าหน้าที่ ผู้ยืม', 'เจ้าหน้าที่เลือกชิ้นจริงตอนจัดเตรียม ผู้ยืมตรวจ Serial Number อัปโหลดรูปตอนรับ แล้วยืนยัน ระบบสร้าง UsageLog สถานะ Lended', 'FR-PKP-01 ถึง 03'],
    ]),
    ('wide_image', 'figures/02-return.png',
     'ผังกระบวนการคืนและตรวจสภาพ'),
    ('table', [1.2, 2.4, 8.2, 4.2],
     ['ขั้น', 'ผู้ทำ', 'สิ่งที่ระบบทำ', 'ข้อกำหนด'],
     [
        ['1', 'ผู้ยืม', 'แจ้งคืนผ่านระบบพร้อมอัปโหลดรูปตอนคืน', 'FR-RTN-01'],
        ['2', 'เจ้าหน้าที่', 'เปิดรูปตอนรับเทียบกับสภาพตอนคืน', 'FR-RTN-02'],
        ['3', 'เจ้าหน้าที่', 'บันทึกผลตรวจสภาพ B0-B3 พร้อมหมายเหตุ ระบบเขียนแถวใหม่ใน Inspection และ ConditionLog', 'FR-RTN-03'],
        ['4', 'ระบบ', 'สำหรับ T2 ปฏิเสธการบันทึก ถ้าผู้ประเมินเป็นคนเดียวกับผู้จัดเตรียมของชิ้นนั้น (อ่านผู้จัดเตรียมจาก ConditionLog.LoggedBy ตอนจ่ายของ) ตอบรหัส CANNOT_INSPECT_OWN_PREPARATION', 'FR-RTN-04'],
        ['5', 'ระบบ', 'ถ้าพบความเสียหายระดับ B1 ขึ้นไป คำนวณคะแนนที่ต้องหัก (CreditWeight × 1, 3, 5 ตามระดับ) แล้วสร้างแถวใน PenaltyInfo', 'FR-RTN-05'],
        ['6', 'ระบบ', 'ถ้าคืนหลังเวลาปิดทำการของวันครบกำหนด (ค่าเริ่มต้น 17:00 ผู้ดูแลระบบตั้งได้) นับเป็นคืนช้าเพิ่มหนึ่งวันแล้วคำนวณค่าปรับคืนช้า', 'FR-RTN-07 FR-CRD-03 FR-ADM-04'],
        ['7', 'ระบบ', 'ปิด UsageLog เป็นสถานะ Inspected และคืนทรัพยากรกลับสู่คลัง', 'FR-RTN-03'],
    ]),
    ('wide_image', 'figures/04-renew.png',
     'ผังกระบวนการต่ออายุการยืม'),
    ('table', [1.2, 2.4, 8.2, 4.2],
     ['ขั้น', 'ผู้ทำ', 'สิ่งที่ระบบทำ', 'ข้อกำหนด'],
     [
        ['1', 'ผู้ยืม', 'เปิดตัวเลือกการต่ออายุจากรายการที่ยืมอยู่ ระบบแสดงจำนวนครั้งที่ต่อได้อีก วันครบกำหนดใหม่ที่เลือกได้ และบอกว่าต่อได้ทันทีหรือต้องนำอุปกรณ์มาให้ตรวจ ก่อนยืนยัน (loan.extensionOptions)', 'FR-RNW-05'],
        ['2', 'ระบบ', 'ปฏิเสธถ้ามีคำขอต่ออายุค้างอยู่แล้ว เครดิตอยู่ D3 หรือต่อครบ MaxExtendTime ของคู่ (กฎการยืมและ ระดับเครดิต) แล้ว และตรวจว่าช่วงที่ขอเพิ่มไม่ชนกับการจองของคนถัดไป', 'FR-RNW-01'],
        ['3', 'ระบบ', 'เลือกผู้ตัดสินจากตารางเลือกผู้ตัดสิน (ตารางถัดไป) แล้วสร้างแถวใน ExtensionRequest พร้อมครั้งที่ (ExtendNo) กำหนดคืนเดิม และเหตุผล', 'FR-RNW-02 03 06'],
        ['4', 'เจ้าหน้าที่ หรือ อาจารย์', 'อนุมัติหรือปฏิเสธจากคิวของตน ผู้ตัดสินต้องไม่ใช่ผู้ขอ เจ้าหน้าที่ตัดสินคำขอที่ต้องส่งอาจารย์ไม่ได้', 'FR-RNW-03'],
        ['5', 'ระบบ', 'เมื่ออนุมัติ เลื่อน DueTime ใน UsageLog แล้วแจ้งผู้ยืม', 'FR-RNW-01 FR-NTF-01'],
    ]),
    ('p',
     'ตารางเลือกผู้ตัดสินการต่ออายุ อ่านจากบนลงล่าง ข้อแรกที่ตรงคือคำตอบ'),
    ('table', [4.4, 5.6, 6.2],
     ['เงื่อนไข', 'ผู้ตัดสิน', 'หมายเหตุ'],
     [
        ['อุปกรณ์ T2 หรือเครดิต D2-D3', 'อาจารย์', 'ตรง FR-RNW-03 และ FR-RNW-06'],
        ['อุปกรณ์ T0', 'อนุมัติทันที', '—'],
        ['อุปกรณ์ T1', 'ครั้งคี่อนุมัติทันที\nครั้งคู่เจ้าหน้าที่ (ต้องนำอุปกรณ์มาตรวจ)', 'ตรง FR-RNW-02'],
        ['สถานที่ T3 และกฎที่อ่านระดับไม่ได้', 'เจ้าหน้าที่', 'ต่างจาก FR-RNW-04 ที่ให้ต่อได้ทันทีถ้าสล็อตถัดไปว่าง'],
    ]),
    ('note',
     'เหลือแถวเดียวที่ต่างจาก SRS คือสถานที่ T3 ต้องตัดสินว่าจะแก้โค้ดให้ตรง FR-RNW-04 หรือแก้ SRS ให้ตรงข้อเสนอโครงการ §5.7 ที่โค้ดอ้างถึง'),
    ('wide_image', 'figures/03-appeal.png',
     'ผังกระบวนการอุทธรณ์'),
    ('table', [1.2, 2.4, 8.2, 4.2],
     ['ขั้น', 'ผู้ทำ', 'สิ่งที่ระบบทำ', 'ข้อกำหนด'],
     [
        ['1', 'ผู้ยืม', 'ยื่นอุทธรณ์ภายใน 7 วันนับจากวันที่เจ้าหน้าที่รายงานผล พร้อมเหตุผลและรูปเพิ่มเติม', 'FR-APL-01 FR-APL-02'],
        ['2', 'ระบบ', 'สร้างแถวใน AppealInfo ผูกกับบทลงโทษเดิม หนึ่งบทลงโทษยื่นได้ครั้งเดียว', 'FR-APL-01'],
        ['3', 'อาจารย์', 'ดูรูปก่อน-หลัง รายงานตรวจสภาพของเจ้าหน้าที่ (ระดับที่ให้ หมายเหตุ ผู้ตรวจ และเวลา) และหลักฐานของผู้ยืม จากหน้าจอเดียว', 'FR-APL-03'],
        ['4', 'ระบบ', 'ปฏิเสธไม่ให้ผู้ประเมินคนเดิมเป็นผู้ตัดสินอุทธรณ์', 'FR-APL-04'],
        ['5', 'อาจารย์', 'ตัดสิน ถ้าให้ผ่าน เลือกได้ว่าจะยกเลิกบทลงโทษ กำหนดจำนวนเครดิตที่ยังหัก หรือปรับระดับความเสียหายให้ต่ำกว่าที่ตรวจ ระบบคิดบทลงโทษของระดับใหม่แบบเดียวกับตอนตรวจ (PenaltyRule ก่อน แล้วจึงสูตร CreditWeight คูณระดับ) ปิดบทลงโทษเดิม สร้างแถวใหม่ถ้ายังมีค่าหัก คืนเครดิตส่วนต่าง และเก็บระดับที่ปรับไว้ในการอุทธรณ์ โดยไม่แก้ผลตรวจเดิม', 'FR-APL-05 FR-APL-06'],
    ]),
    ('h1', '3. System Specification'),
    ('h2', '3.1 Purpose'),
    ('p',
     'หัวข้อนี้ระบุว่าใครใช้ระบบบ้าง แต่ละคนทำอะไรได้ และยูสเคสหลักแต่ละตัวทำงานอย่างไรทีละขั้น'),
    ('h2', '3.2 Actors'),
    ('table', [3.0, 4.4, 5.2, 3.6],
     ['ผู้กระทำ', 'คือใคร', 'ทำอะไรได้', 'ระดับความรู้'],
     [
        ['Borrower\n(ผู้ยืม)', 'นิสิตและบุคลากรที่มีบัญชีของมหาวิทยาลัย', 'ค้นหา ยืม รับ คืน ต่ออายุ อุทธรณ์ ดูเครดิตของตนเอง', 'ผู้ใช้ทั่วไป'],
        ['Staff\n(เจ้าหน้าที่)', 'เจ้าหน้าที่ประจำภาควิชาหรือชมรม', 'จัดการบัญชีอุปกรณ์ จัดเตรียมและจ่ายของ รับคืน ตรวจสภาพ บันทึกการซ่อม ตัดสินการต่ออายุที่ต้องตรวจสภาพ', 'ผ่านการอบรมเบื้องต้น'],
        ['Supervisor\n(อาจารย์)', 'อาจารย์ผู้ดูแลหน่วยงาน', 'ทำได้ทุกอย่างที่เจ้าหน้าที่ทำ และอนุมัติคำขอ T2 ตัดสินการต่ออายุ T2 และการอุทธรณ์', 'ผู้ใช้ทั่วไป'],
        ['Admin\n(ผู้ดูแลระบบ)', 'ผู้ดูแลระบบของภาควิชา', 'จัดการผู้ใช้และบทบาท ตั้งค่าระบบ สั่งงานตามเวลา ดู Audit Log และรายงาน', 'มีความรู้ด้าน IT'],
        ['System\n(ระบบ)', 'งานที่ทำงานตามเวลาโดยไม่มีคนสั่ง', 'งานตามเวลา 6 งาน: ทำเครื่องหมายคืนช้าและของหาย ยกเลิกคำขอที่ไม่มารับ หมดอายุบทลงโทษ เตือนใกล้ครบกำหนดทั้งในระบบและอีเมล เปิดรอบตรวจห้อง T3', '—'],
    ]),
    ('note',
     'เจ้าหน้าที่และอาจารย์ทำสิ่งที่ผู้ยืมทำได้ทั้งหมดด้วย (FR-AUTH-04) และทั้งสองบทบาททำงานได้เฉพาะกับทรัพยากรของหน่วยงานตนเองเท่านั้น (FR-AUTH-05)'),
    ('h2', '3.3 Use Case Diagram'),
    ('image', 'figures/usecase.png', 13.6,
     'แผนภาพยูสเคสของระบบ ULMs «include» คือยูสเคสที่ถูกเรียกใช้เสมอ และ «extend» คือยูสเคสที่ทำงานเพิ่มในบางเงื่อนไข'),
    ('h2', '3.4 Use Case Specification'),
    ('p',
     'ยกมาสามยูสเคสที่มีเส้นทางรองมากที่สุด ส่วนยูสเคสอื่นดูลำดับขั้นได้จากตารางใต้ผังกระบวนการในหัวข้อ 2.3.2'),
    ('h2', 'UC-03 ส่งคำขอยืม'),
    ('table', [3.4, 12.6],
     ['หัวข้อ', 'รายละเอียด'],
     [
        ['ผู้กระทำหลัก', 'ผู้ยืม'],
        ['เงื่อนไขก่อนเริ่ม', 'ผู้ใช้เข้าสู่ระบบแล้ว และมีสิทธิ์เข้าใช้ทรัพยากรที่ต้องการตามตาราง Eligibility'],
        ['เส้นทางหลัก', '1) เลือกอุปกรณ์เข้าตะกร้าได้หลายรายการ\n2) ระบุวันที่รับและวันที่คืน\n3) ระบบตรวจระยะเวลา 1-14 วันและไม่เกินเพดาน (กฎการยืมและ ระดับเครดิต)\n4) ระบบตรวจเครดิตและของคงเหลือ\n5) ระบบตัดสินเส้นทางอนุมัติตามระดับอุปกรณ์\n6) บันทึกคำขอ เส้นทางอัตโนมัติเป็น Approved และแจ้งเจ้าหน้าที่ให้เตรียมของ เส้นทางอาจารย์เป็น Pending และแจ้งอาจารย์ของหน่วยงาน'],
        ['เส้นทางรอง', '4a) ของถูกคนอื่นตัดหน้าระหว่างกด → ยกเลิกทั้งรายการแล้วให้เลือกใหม่\n5a) เป็นอุปกรณ์ T0 → อนุมัติทันทีโดยไม่ต้องรออาจารย์'],
        ['เงื่อนไขหลังจบ', 'มีแถวใน Reservations สถานะ Pending หรือ Approved และของถูกกันไว้แล้ว'],
        ['ข้อกำหนดที่ตอบ', 'FR-REQ-01 ถึง FR-REQ-10'],
        ['สถานะการพัฒนา', 'ใช้งานได้จริง: loan.create สำหรับอุปกรณ์ และ loan.createRoomBooking สำหรับห้อง ชุดทดสอบผ่านเบราว์เซอร์ยืนยันการส่งคำขอและกฎว่า T0 จองล่วงหน้าไม่ได้'],
    ]),
    ('h2', 'UC-06 ต่ออายุการยืม'),
    ('table', [3.4, 12.6],
     ['หัวข้อ', 'รายละเอียด'],
     [
        ['ผู้กระทำหลัก', 'ผู้ยืม เจ้าหน้าที่ และอาจารย์'],
        ['เงื่อนไขก่อนเริ่ม', 'มีการถือครองสถานะ Lended และยังไม่มีคำขอต่ออายุค้างอยู่'],
        ['เส้นทางหลัก', '1) ผู้ยืมเปิดตัวเลือกการต่ออายุ ดูวันครบกำหนดใหม่และประเภทการต่อ\n2) ผู้ยืมเลือกวันและใส่เหตุผล แล้วยืนยัน\n3) ระบบเลือกผู้ตัดสินตามตารางเลือกผู้ตัดสิน\n4) ผู้ตัดสินอนุมัติ ระบบเลื่อน DueTime และแจ้งผู้ยืม'],
        ['เส้นทางรอง', '3a) เส้นทางอนุมัติทันที → เลื่อนกำหนดทันทีโดยไม่เข้าคิว\n3b) ต่อครบจำนวนครั้งแล้ว หรือเครดิต D3 → ปฏิเสธพร้อมบอกเหตุผล\n3c) ช่วงที่ขอชนการจองของคนถัดไป → ปฏิเสธ\n4a) ผู้ยืมยกเลิกคำขอก่อนมีคนตัดสิน'],
        ['เงื่อนไขหลังจบ', 'มีแถวใน ExtensionRequest สถานะ Approved Rejected หรือ Canceled และ DueTime ใน UsageLog ตรงกับผลการตัดสิน'],
        ['ข้อกำหนดที่ตอบ', 'FR-RNW-01 ถึง FR-RNW-06 (ดูข้อต่างจาก SRS ในหัวข้อ 2.3.2)'],
        ['สถานะการพัฒนา', 'ใช้งานได้จริง หน้าจอผู้ยืมเรียก loan.requestExtension แล้ว'],
    ]),
    ('h2', 'UC-07 คืนอุปกรณ์และตรวจสภาพ'),
    ('table', [3.4, 12.6],
     ['หัวข้อ', 'รายละเอียด'],
     [
        ['ผู้กระทำหลัก', 'ผู้ยืม และเจ้าหน้าที่'],
        ['เงื่อนไขก่อนเริ่ม', 'มีการถือครองสถานะ Lended อยู่'],
        ['เส้นทางหลัก', '1) ผู้ยืมแจ้งคืนพร้อมอัปโหลดรูปตอนคืน\n2) เจ้าหน้าที่เทียบรูปก่อน-หลัง\n3) บันทึกผลตรวจสภาพพร้อมหมายเหตุ\n4) ระบบปิดการถือครองเป็นสถานะ Inspected และคืนของเข้าคลัง'],
        ['เส้นทางรอง', '3a) พบความเสียหายเกินระดับปกติ → ระบบคำนวณคะแนนที่หักแล้วสร้างบทลงโทษ\n3b) อุปกรณ์ T2 และผู้ตรวจเป็นคนเดียวกับผู้จัดเตรียม → ระบบปฏิเสธ\n4a) คืนหลังเวลาปิดทำการของวันครบกำหนด → นับเป็นคืนช้าเพิ่มหนึ่งวัน'],
        ['เงื่อนไขหลังจบ', 'ทรัพยากรกลับเป็น InStorage และคะแนนเครดิตของผู้ยืมถูกคำนวณใหม่ถ้ามีบทลงโทษ'],
        ['ข้อกำหนดที่ตอบ', 'FR-RTN-01 ถึง FR-RTN-07'],
        ['สถานะการพัฒนา', 'ใช้งานได้จริง'],
    ]),
    ('h1', '4. System Analysis and Design'),
    ('h2', '4.1 Purpose'),
    ('p',
     'หัวข้อนี้แปลงยูสเคสในหัวข้อ 3 ให้เป็นส่วนประกอบที่เขียนโค้ดได้ ยูสเคสหนึ่งตัวถูกทำให้เป็นจริงด้วยหน้าจอใด เรียก procedure ใด และแตะตารางใดบ้าง พร้อมรายการฟังก์ชันทั้งหมดของระบบและแบบจำลองฐานข้อมูล'),
    ('h2', '4.2 Design Model'),
    ('h2', '4.2.1 Use Case Realizations'),
    ('p',
     'แต่ละยูสเคสถูกทำให้เป็นจริงด้วยสามชั้นเสมอ: หน้าจอฝั่งผู้ใช้ procedure ฝั่งเซิร์ฟเวอร์ ตารางในฐานข้อมูล ตารางนี้คือแผนที่ที่ผูกสามอย่างเข้าด้วยกัน'),
    ('table', [2.6, 3.8, 4.8, 5.0],
     ['ยูสเคส', 'หน้าจอ', 'procedure ฝั่งเซิร์ฟเวอร์', 'ตารางที่แตะ'],
     [
        ['UC-01 เข้าสู่ระบบ', '/login /register /verify-email /forgot-password /reset-password /profile', 'auth.login auth.me auth.logout auth.logoutAll auth.register auth.verifyEmail auth.requestPasswordReset auth.resetPasswordWithToken auth.changePassword', 'AccountInfo RoleInfo SessionInfo EmailVerification PasswordReset AuditLog'],
        ['UC-02 ค้นหาอุปกรณ์', '/catalog /catalog/:id /rooms', 'item.list item.getById item.getAvailability item.listUnits item.listRooms item.getRoomById item.roomAvailability', 'ResourceInfo ItemInfo ItemIndiv RoomInfo Eligibility'],
        ['UC-03 ส่งคำขอยืม', '/request /my/loans', 'loan.create loan.list loan.getById loan.cancel', 'Reservations BorrowConstraints CreditTier'],
        ['UC-04 อนุมัติคำขอ', '/supervisor/approvals', 'approval.queue approval.counts approval.decide', 'Reservations Notification'],
        ['UC-05 จ่ายอุปกรณ์', '/staff /staff/handover/:usageKey /pickup', 'loan.staffQueue loan.queueCounts loan.allocate loan.swapUnit loan.confirmPickup loan.confirmMyPickup image.requestUsagePhotoUpload image.attachUsagePhotos', 'UsageLog ItemIndiv ConditionLog Images'],
        ['UC-06 ต่ออายุ', '/my/loans /staff /supervisor/approvals', 'loan.extensionOptions loan.requestExtension loan.myExtensions loan.cancelExtension loan.extensionReviews loan.decideExtension approval.extensionQueue approval.decideExtension', 'ExtensionRequest UsageLog Reservations Notification'],
        ['UC-07 คืนและตรวจสภาพ', '/staff /staff/inspection', 'loan.recordReturn loan.markLost inspection.create inspection.listForResource', 'UsageLog Inspection ConditionLog PenaltyInfo Images'],
        ['UC-08 อุทธรณ์', '/my/appeals /supervisor/appeals', 'appeal.appealable appeal.create appeal.mine appeal.getById appeal.list appeal.decide', 'AppealInfo PenaltyInfo Images Notification'],
        ['UC-10 จองห้อง', '/rooms /rooms/:id/book /rooms/use', 'item.roomAvailability loan.createRoomBooking', 'Reservations RoomInfo'],
        ['UC-11 แจ้งเตือน', 'แถบแจ้งเตือนทุกหน้า และอีเมล', 'notification.list notification.unreadCount notification.markRead notification.markAllRead', 'Notification AccountInfo'],
        ['UC-13 และ UC-14 ผู้ใช้และค่าตั้ง', '/admin/users /admin/config /staff/settings', 'admin.listUsers admin.getUserById admin.getUserLoans admin.getLendingSettings admin.updateLendingSettings admin.updateWorkHours', 'AccountInfo UsageLog BorrowConstraints SystemSetting'],
        ['UC-15 รายงาน', '/admin/reports /reports/analytics /reports/export', 'report.summary admin.listAudit admin.getAuditById', 'Reservations UsageLog Inspection PenaltyInfo AuditLog'],
    ]),
    ('h2', '4.2.2 Function Specification'),
    ('p',
     'ระบบมีฟังก์ชันที่เรียกใช้ได้จริง 111 รายการใน 11 โดเมน แต่ละรายการประกาศรูปร่างข้อมูลเข้าและออกด้วย zod schema ซึ่งตรวจก่อนถึงตรรกะทางธุรกิจเสมอ'),
    ('table', [2.4, 1.6, 7.4, 4.6],
     ['โดเมน', 'จำนวน', 'ฟังก์ชัน', 'สิทธิ์ขั้นต่ำ'],
     [
        ['auth', '10', 'login me logout logoutAll providers register verifyEmail requestPasswordReset resetPasswordWithToken changePassword', 'สาธารณะ / ผู้ใช้ที่ล็อกอิน'],
        ['admin', '18', 'จัดการผู้ใช้ 9 (รวมประวัติการยืม) ค่าตั้งการยืม 3 (รวมเวลาทำการ) ค่าตั้งเชิงเทคนิค 1 สถานะระบบ 1 งานตามเวลา 2 audit 2', 'admin (listUsersInScope และค่าตั้งการยืมเปิดให้ staff)'],
        ['item', '29', 'ฝั่งผู้ยืม: ค้นหา ดูรายละเอียด ของคงเหลือ รายการชิ้น สถานที่ ช่วงเวลาว่างของห้อง — ฝั่งเจ้าหน้าที่: สร้าง แก้ไข และลบประเภท ชิ้น และสถานที่ เปิด-ปิดการให้ยืม ปรับสภาพ กำหนดสิทธิ์การเข้าใช้ ขอและยกเลิกการปลดระวาง รายการระดับ กลุ่ม และบทบาทอำนาจ', 'ผู้ใช้ที่ล็อกอิน / staff'],
        ['loan', '20', 'ฝั่งผู้ยืม: create createRoomBooking list getById cancel confirmMyPickup extensionOptions requestExtension myExtensions cancelExtension — ฝั่งเจ้าหน้าที่: staffQueue queueCounts getForStaff allocate swapUnit confirmPickup recordReturn markLost extensionReviews decideExtension', 'ผู้ใช้ที่ล็อกอิน / staff'],
        ['approval', '7', 'queue counts decide extensionQueue decideExtension retirementQueue decideRetirement', 'staff (T2 และการปลดระวางตัดสินได้เฉพาะอาจารย์ ตรวจรายแถว)'],
        ['inspection', '9', 'list getById create listForResource listRoomRounds recordRoomCheck listRepairs startRepair finishRepair', 'staff'],
        ['notification', '4', 'list unreadCount markRead markAllRead', 'ผู้ใช้ที่ล็อกอิน'],
        ['appeal', '6', 'appealable create mine getById list decide', 'ผู้ใช้ที่ล็อกอิน / supervisor'],
        ['credit', '2', 'me getById', 'ผู้ใช้ที่ล็อกอิน / staff'],
        ['report', '1', 'summary (รวมสถิติความเสียหายและการใช้ห้อง 30 วันล่าสุด)', 'staff (เห็นเฉพาะหน่วยงานของตน) / admin'],
        ['image', '5', 'requestUpload requestUsagePhotoUpload attachUsagePhotos usagePhotos detachUsagePhoto', 'ผู้ใช้ที่ล็อกอิน / staff'],
    ]),
    ('p',
     'ทุกกลุ่มความต้องการใน SRS มีฟังก์ชันฝั่งเซิร์ฟเวอร์รองรับแล้ว นอกจาก tRPC ยังมีเส้นทาง HTTP ธรรมดาสองกลุ่ม คือ /auth/google สำหรับเข้าสู่ระบบด้วยบัญชีมหาวิทยาลัย (ปิดไว้จนกว่าจะตั้ง GOOGLE_*) และ /media สำหรับเสิร์ฟรูป'),
    ('p',
     'งานตามเวลามี 6 งาน ทุกครั้งที่รันบันทึกผลลงตาราง CronRunLog และผู้ดูแลระบบสั่งรันเองได้จาก admin.runCronJob สองงานที่เคยวางไว้ (computeAvailability และ rollupDailyStats) ตัดออกแล้ว เพราะของคงเหลือและรายงานคำนวณสดด้วย SQL ได้เร็วพอ'),
    ('table', [4.6, 7.0, 4.4],
     ['งาน', 'ทำอะไร', 'สถานะ'],
     [
        ['markOverdue', 'ทำเครื่องหมายการยืมที่เลยกำหนดคืน', 'ใช้งานได้จริง'],
        ['markLost', 'แจ้งของหายเมื่อเลยกำหนด 2 สัปดาห์', 'ใช้งานได้จริง'],
        ['expireDemerits', 'หมดอายุบทลงโทษที่ครบระยะ', 'ใช้งานได้จริง'],
        ['dueSoonReminder', 'แจ้งเตือนก่อนครบกำหนดคืน 2 วันทั้งในระบบและอีเมล และแจ้งเจ้าหน้าที่เรื่องของที่ครบกำหนดคืนภายใน 1 วัน', 'ใช้งานได้จริง'],
        ['expireStaleRequests', 'ยกเลิกคำขอที่ไม่มารับ รวมที่จัดเตรียมไว้แล้ว และปล่อยของกลับคลัง', 'ใช้งานได้จริง'],
        ['openT3InspectionRounds', 'เปิดรอบตรวจสภาพห้อง T3 ทุก 30 วัน ให้ทำภายใน 7 วัน และแจ้งเจ้าหน้าที่ (FR-RTN-06 ตาม SRS v1.1)', 'ใช้งานได้จริง'],
    ]),
    ('p',
     'สัญญาข้อผิดพลาด — ชั้น service รหัสสองชั้นพร้อมกัน'),
    ('table', [4.6, 4.6, 6.8],
     ['ชนิดของปัญหา', 'รหัสมาตรฐาน', 'ตัวอย่างรหัสเชิงธุรกิจ'],
     [
        ['ยังไม่ได้เข้าสู่ระบบ รหัสผ่านผิด', 'UNAUTHORIZED', 'NOT_AUTHENTICATED INVALID_CREDENTIALS'],
        ['บทบาทไม่พอ อยู่นอกหน่วยงานที่ดูแล ทำงานของตัวเอง', 'FORBIDDEN', 'ROLE_NOT_ALLOWED OUT_OF_MANAGEMENT_SCOPE CANNOT_APPROVE_OWN_REQUEST CANNOT_INSPECT_OWN_PREPARATION'],
        ['ของถูกตัดหน้า สถานะไม่ถูกจังหวะ', 'CONFLICT', 'RESOURCE_IN_USE WRONG_LOAN_STATE WINDOW_NOT_AVAILABLE EXTENSION_ALREADY_PENDING'],
        ['ไม่พบข้อมูล', 'NOT_FOUND', 'ITEM_NOT_FOUND LOAN_NOT_FOUND EXTENSION_NOT_FOUND'],
        ['ลองเข้าสู่ระบบถี่เกินไป', 'TOO_MANY_REQUESTS', 'TOO_MANY_ATTEMPTS'],
    ]),
    ('note',
     'ฝั่งเซิร์ฟเวอร์มีรหัสเชิงธุรกิจ 104 ตัว หน้าเว็บมีคำแปลไทย 103 ตัว ตัวที่ขาดคือ INVALID_CURSOR ซึ่งผู้ใช้ไม่เห็นในการใช้งานปกติ'),
    ('p',
     'การอัปเดตข้อมูลใช้การถามซ้ำตามรอบ ไม่ใช้ WebSocket ของคงเหลือและสล็อตเวลาทุก 15 วินาที สถานะคำขอและคิวเจ้าหน้าที่ทุก 30 วินาที การแจ้งเตือนและคิวอาจารย์ทุก 60 วินาที'),
    ('h2', '4.3 Business Object Diagrams'),
    ('image', 'figures/business-objects.png', 15.6,
     'แผนภาพ Business Object กล่องเข้มคือวัตถุแกนกลางที่กระบวนการอื่นอ้างถึง'),
    ('table', [3.6, 5.4, 7.0],
     ['Business Object', 'หมายถึง', 'กฎที่ผูกติดมาด้วย'],
     [
        ['Resource', 'สิ่งที่ยืมได้หนึ่งหน่วย', 'ผูกกับกฎการยืมหนึ่งชุดและหน่วยงานที่ดูแลหนึ่งกลุ่มเสมอ'],
        ['Reservation', 'คำขอยืมหรือการจองหนึ่งครั้ง', 'มีกำหนดเวลามารับ ถ้าเลยกำหนดต้องถูกยกเลิกอัตโนมัติ'],
        ['UsageLog', 'การถือครองจริงหนึ่งครั้ง', 'เกิดเมื่อของออกจากคลังเท่านั้น เก็บสภาพตอนรับและตอนคืนแยกกัน'],
        ['Extension', 'คำขอต่ออายุหนึ่งครั้ง', 'นับครั้งจาก 1 ต่อหนึ่งการถือครอง เส้นทางอนุมัติขึ้นกับครั้งที่'],
        ['Penalty', 'การหักเครดิตหนึ่งครั้ง', 'คะแนนปัจจุบันคือผลรวมของแถวที่ยังมีผล'],
        ['Appeal', 'การอุทธรณ์หนึ่งครั้ง', 'หนึ่งบทลงโทษอุทธรณ์ได้ครั้งเดียว ไม่ลบของเดิมแต่สร้างของใหม่'],
    ]),
    ('h2', '4.4 Database Design Model'),
    ('h2', '4.4.1 Class to Table Mapping'),
    ('p',
     'Business Object ในหัวข้อ 4.3 ลงเป็นตารางจริงอย่างไร'),
    ('table', [3.6, 5.0, 7.4],
     ['Business Object', 'ตารางจริง', 'หมายเหตุ'],
     [
        ['Account', 'AccountInfo', 'แยกบทบาทออกไปเป็นตาราง RoleInfo อำนาจในหน่วยงานอยู่ที่ Authority'],
        ['Resource', 'ResourceInfo + ItemIndiv + RoomInfo', 'หนึ่งต่อหนึ่งทั้งสองทาง บังคับด้วย unique index'],
        ['ItemType', 'ItemInfo', 'ประเภทอุปกรณ์ มูลค่าเครดิตที่ใช้คำนวณค่าปรับอยู่ที่นี่'],
        ['BorrowPolicy', 'BorrowRule + BorrowConstraints + PenaltyRule', 'แยกเป็นคู่ (กฎและ ระดับเครดิต) จึงปรับรายระดับได้'],
        ['Reservation', 'Reservations', 'ครอบคลุมทั้งคำขอยืมและการจองล่วงหน้าในตารางเดียว'],
        ['UsageLog', 'UsageLog', 'อ้างกลับไปยัง Reservations ที่เป็นต้นทาง'],
        ['Extension', 'ExtensionRequest', 'เก็บครั้งที่ กำหนดคืนเดิม กำหนดคืนที่ขอ และเหตุผล'],
        ['Inspection', 'Inspection + ConditionLog', 'ผลตรวจกับสภาพที่บันทึกแยกตารางกัน เพื่อให้สภาพถูกอ้างซ้ำได้'],
        ['Penalty', 'PenaltyInfo', 'หนึ่งแถวคือหนึ่ง Demerit Event'],
        ['Appeal', 'AppealInfo', 'ชี้ทั้งบทลงโทษเดิมและบทลงโทษใหม่ และเก็บระดับความเสียหายที่อาจารย์ปรับ'],
        ['Evidence', 'Images', 'แยกชนิดด้วย SubmissionType ว่าเป็นรูปตอนรับ ตอนคืน หรือตอนตรวจ'],
    ]),
    ('table', [4.0, 5.2, 6.8],
     ['ศัพท์ใน SRS', 'ที่เก็บจริง', 'หมายเหตุ'],
     [
        ['Tier (T0-T3)', 'BorrowRule.RuleName', 'เหลือระบบเดียวแล้ว ItemInfo.CreditWeight ใช้คำนวณค่าปรับเท่านั้น'],
        ['Credit Band (D0-D3)', 'ตาราง CreditTier (CreditMin, CreditMax)', 'เป็นตาราง ไม่ใช่ enum จึงปรับช่วงคะแนนได้โดยไม่ต้องแก้โค้ด'],
        ['Allocation', 'Reservations แล้วต่อด้วย UsageLog', 'Reservations = คำขอ UsageLog = การถือครองจริง'],
        ['Demerit Event', 'PenaltyInfo หนึ่งแถว', 'คะแนนเครดิตคือผลรวมของแถวที่ยังมีผล (FR-CRD-06)'],
        ['B0-B3 (ความเสียหาย 4 ระดับ)', 'enum ConditionType', 'B0 Normal B1 MinorDamage B2 MajorDamage B3 Broken ค่า Missing ใช้กับของหายเท่านั้น'],
        ['work_time', 'ตาราง SystemSetting คีย์ workHours', 'เวลาทำการของเคาน์เตอร์ ค่าเริ่มต้น 08:00-17:00 แก้ได้ด้วย admin.updateWorkHours ค่าเชิงเทคนิคอื่นยังเป็นตัวแปรสภาพแวดล้อม (FR-ADM-04)'],
    ]),
    ('h2', '4.4.2 ER-Diagrams'),
    ('image', 'figures/er.png', 15.6,
     'แผนภาพความสัมพันธ์ของข้อมูล (Entity Relationship Diagram) ของระบบ ULMs'),
    ('note',
     'ภาพนี้เป็นรุ่นที่ใช้ตอนออกแบบ (DatabaseDesign4) สคีมาที่ใช้จริงเพิ่มตาราง SessionInfo AuditLog CronRunLog PasswordReset EmailVerification RetirementRequest RoomCheckRound และ SystemSetting รวมเป็น 35 ตาราง รายการเต็มอยู่ในหัวข้อ 4.4.3'),
    ('h2', '4.4.3 Data Dictionary'),
    ('p',
     'ฐานข้อมูลเป็น PostgreSQL เข้าถึงผ่าน Prisma ทั้งหมด ปัจจุบันมี 35 ตาราง 9 ชนิดข้อมูลแบบ enum และ 28 migration'),
    ('table', [3.4, 6.2, 6.4],
     ['ตาราง', 'ฟิลด์สำคัญ', 'หน้าที่และข้อสังเกต'],
     [
        ['AccountInfo', 'AccountKey (PK) Email (unique) UserID (unique) HashedPassword UserCredit ฯลฯ', 'ผู้ใช้หนึ่งคน IsActive ใช้ระงับบัญชีโดยไม่ลบประวัติ'],
        ['RoleInfo', 'RoleKey (PK) RoleName', 'บทบาทระดับระบบ 4 บทบาท'],
        ['FacultyInfo BranchInfo ClubInfo ManagementGroup', 'คีย์หลักของแต่ละตาราง ชื่อหน่วยงาน ความสัมพันธ์ไปยังกลุ่มผู้ดูแล', 'โครงหน่วยงาน ManagementGroup เป็นตัวแทนร่วมของภาควิชาและชมรม'],
        ['Authority / AuthorityRole', 'AuthorityKey AccountKey ManageGroupKey AuthorityLevel', 'อำนาจของผู้ใช้ในหน่วยงาน — เป็นฐานของการจำกัดขอบเขตเจ้าหน้าที่'],
        ['ItemInfo ItemIndiv RoomInfo', 'ItemInfo: ItemKey ItemName CreditWeight — ItemIndiv: IndivKey ResourceKey (unique) ItemID — RoomInfo: RoomKey ResourceKey (unique) RoomName RoomLocation', 'ItemID คือ Serial Number ทั้งของและสถานที่ผูกกลับไปที่ ResourceInfo แบบหนึ่งต่อหนึ่ง'],
        ['ResourceInfo', 'ResourceKey (PK) ManagedBy BorrowRule ConditionKey ResourceStatus ฯลฯ', 'สิ่งที่ยืมได้ BufferTime คือ prep_days'],
        ['ConditionLog RepairLog Images Notification', 'ConditionLog: ResourceKey Condition LoggedBy — RepairLog: ช่วงเวลาซ่อม สภาพก่อน-หลัง — Images: SubmissionType ImageURL ผูกกับ UsageLog หรือ Inspection — Notification: NotificationType ReadAt DedupeKey', 'บันทึกประกอบที่ทุกกระบวนการเขียนเพิ่มระหว่างทาง ConditionLog.LoggedBy ตอนจ่ายของคือผู้จัดเตรียม'],
        ['BorrowRule BorrowConstraints PenaltyRule CreditTier Eligibility', 'BorrowConstraints: BorrowRuleKey + CreditTierKey → MaxBorrowDate MaxExtendTime MinimumAuthorityLevel — PenaltyRule: PenaltyReason → PenaltyAmount PenaltyLength — CreditTier: CreditMin CreditMax — Eligibility: ResourceKey + GroupKey + RoleKey', 'กฎการยืมทั้งหมด BorrowConstraints เป็นตารางคู่ (กฎและ ระดับเครดิต)'],
        ['Reservations', 'ReservationKey (PK) ResourceKey ReservedBy StartTime EndTime ฯลฯ', 'คำขอและการจอง ReservationExpiration คือกำหนดมารับ'],
        ['UsageLog', 'UsageKey (PK) ReservationKey AccountKey ResourceKey CurrentStatus DueTime PendingExtension ฯลฯ', 'การถือครองจริง เก็บสภาพตอนรับและตอนคืนคนละคอลัมน์'],
        ['ExtensionRequest', 'ExtensionKey (PK) UsageKey RequestedBy ExtendNo PreviousDueTime RequestedDueTime ApproveStatus Reason ฯลฯ', 'คำขอต่ออายุ มีดัชนี (ApproveStatus, RequestedAt) สำหรับคิว และ (UsageKey) สำหรับนับครั้ง'],
        ['Inspection', 'InspectionKey (PK) UsageKey InspectorKey ConditionKey AppealKey ฯลฯ', 'ผลการตรวจสภาพ'],
        ['PenaltyInfo', 'PenaltyKey (PK) AccountKey UsageKey CreditDeducted ExpirationTime ฯลฯ', 'บทลงโทษหนึ่งครั้ง'],
        ['AppealInfo', 'AppealKey (PK) OriginalPenalty (unique) NewPenalty RevisedCondition FiledBy ResolvedBy ฯลฯ', 'การอุทธรณ์ RevisedCondition คือระดับที่อาจารย์ปรับ ว่างถ้าไม่ได้ปรับ ส่วน ConditionLog ของการตรวจเดิมคงไว้ตามที่ตรวจ'],
        ['SessionInfo AuditLog', 'SessionInfo: TokenHash (unique) ExpiresAt RevokedAt — AuditLog: At ActorName ActorRole Action Target Ip', 'SessionInfo เก็บค่าแฮชของรหัส session ไม่ใช่ตัวรหัส'],
        ['PasswordReset EmailVerification', 'AccountKey TokenHash IssuedAt ExpiresAt UsedAt', 'ลิงก์ลืมรหัสผ่านและยืนยันอีเมล เก็บเฉพาะค่าแฮชของโทเค็น ใช้ได้ครั้งเดียว'],
        ['RetirementRequest RoomCheckRound', 'RetirementRequest: ResourceKey RequestedBy ApproveStatus DecidedBy DecisionNote — RoomCheckRound: ResourceKey OpenedAt DueAt ClosedAt ConditionKey', 'คำขอปลดระวางที่อาจารย์ตัดสิน (FR-EQP-08) และรอบตรวจห้อง T3'],
        ['CronRunLog SystemSetting', 'CronRunLog: RunKey (PK) Job StartedAt FinishedAt Result Affected Detail — SystemSetting: Key (PK) Value', 'ผลการรันงานตามเวลาทุกครั้ง และค่าตั้งระบบที่ผู้ดูแลแก้ได้ เช่น เวลาทำการ'],
    ]),
    ('p',
     'ข้อบังคับความถูกต้องที่ฐานข้อมูลหรือชั้น service เป็นผู้บังคับ'),
    ('table', [5.6, 4.6, 5.8],
     ['ข้อบังคับ', 'บังคับที่ไหน', 'ป้องกันอะไร'],
     [
        ['Email และ UserID ต้องไม่ซ้ำ', 'unique index', 'บัญชีซ้ำจากการสมัครพร้อมกันสองครั้ง'],
        ['AppealInfo.OriginalPenalty ต้องไม่ซ้ำ', 'unique index', 'บทลงโทษหนึ่งครั้งอุทธรณ์ได้ครั้งเดียว'],
        ['SessionInfo.TokenHash ต้องไม่ซ้ำ', 'unique index', 'session ซ้ำค่า'],
        ['การจัดสรรของและการต่ออายุอยู่ใน transaction ระดับ serializable', 'ชั้น service', 'สองคนได้ช่วงเวลาเดียวกันของชิ้นเดียวกันเมื่อกดพร้อมกัน (FR-REQ-09)'],
        ['ผู้อนุมัติต้องไม่ใช่ผู้ขอ ผู้ตัดสินอุทธรณ์ต้องไม่ใช่ผู้ประเมินเดิม', 'ชั้น service', 'การอนุมัติงานของตัวเอง (FR-APV-04, FR-APL-04)'],
        ['ผู้ตรวจสภาพ T2 ต้องไม่ใช่ผู้จัดเตรียม', 'ชั้น service', 'การตรวจงานของตัวเอง (FR-RTN-04)'],
        ['Notification (AccountKey, NotificationType, DedupeKey) ต้องไม่ซ้ำ', 'unique index', 'แจ้งเตือนหรืออีเมลซ้ำเมื่องานตามเวลาหรือการเปิดหน้าเว็บทำงานหลายรอบ'],
    ]),
    ('h1', '5. System Decomposition'),
    ('h2', '5.1 การแบ่งชั้นและองค์ประกอบของระบบ'),
    ('p',
     'ระบบแบ่งเป็น 4 ชั้นตามข้อกำหนดของโครงการ แต่ละชั้นสื่อสารกับชั้นถัดไปเท่านั้น'),
    ('table', [2.9, 4.9, 3.9, 4.3],
     ['ชั้น', 'หน้าที่', 'สิ่งที่ใช้จริง', 'ไฟล์'],
     [
        ['Client', 'เรนเดอร์หน้าจอ เก็บแคชฝั่งผู้ใช้ ตรวจฟอร์มชั้นแรก', 'React 18 + Vite + TanStack Query', 'frontend/src/features/'],
        ['API Server', 'รับคำขอ ตรวจสิทธิ์ ตรวจรูปร่างข้อมูล แปลงข้อผิดพลาด', 'nestjs-trpc ที่เส้นทาง /trpc', 'backend/src/*/*.router.ts'],
        ['Application Server', 'ตรรกะทางธุรกิจ กฎการยืม การคำนวณเครดิต งานตามเวลา', 'NestJS service + mapper + @nestjs/schedule', 'backend/src/*/*.service.ts'],
        ['Database Server', 'เก็บข้อมูลถาวร บังคับความถูกต้องระดับข้อมูล', 'PostgreSQL ผ่าน Prisma', 'backend/prisma/schema.prisma'],
    ]),
    ('table', [3.2, 4.4, 2.0, 6.4],
     ['ส่วนของระบบ', 'เทคโนโลยี', 'รุ่น', 'เหตุผลที่เลือก'],
     [
        ['หน้าเว็บ', 'React + Vite', '18.3 / 5', 'ทีมคุ้นเคย build เป็นไฟล์สแตติกวางบน CDN ได้'],
        ['ภาษา', 'TypeScript (strict)', '5.x', 'ชนิดข้อมูลเดียวใช้ร่วมสองฝั่ง (NFR-MNT-01)'],
        ['เซิร์ฟเวอร์', 'NestJS', '11', 'โครงแบบโมดูล เหมาะกับการแบ่งงาน 14 คน'],
        ['สัญญา API', 'nestjs-trpc + @trpc/server', '2.13 / 11.18', 'ใช้ชนิดข้อมูลเป็นสัญญา ไม่ต้องดูแลเอกสาร API แยก'],
        ['ORM', 'Prisma', '7.9', 'migration เป็นไฟล์ prepared statement กัน SQL injection'],
        ['ฐานข้อมูล', 'PostgreSQL', '16+', 'รองรับ transaction ระดับที่กฎการยืมชนกันต้องใช้'],
        ['งานตามเวลา', '@nestjs/schedule', '6', 'รันในโปรเซสเดียวกับเซิร์ฟเวอร์ ไม่ต้องมีบริการแยก'],
        ['Session', 'โทเค็น HMAC-SHA256 ที่เขียนเอง + cookie-parser', '—', 'เซ็นรหัสที่สุ่มมา เก็บในคุกกี้ httpOnly'],
        ['อีเมล', 'nodemailer ผ่าน SMTP', '10', 'ยืนยันอีเมล ลืมรหัสผ่าน และเตือนใกล้ครบกำหนด ตอนพัฒนาใช้ MailHog'],
        ['การนำขึ้นใช้งาน', 'Docker Compose + nginx', '—', 'ภาพเดียวกันทุกเครื่อง nginx เสิร์ฟหน้าเว็บและส่งต่อ /trpc /api /media /uploads /auth ไปยังเซิร์ฟเวอร์'],
        ['CI', 'GitHub Actions', '—', 'ตรวจรุ่นไลบรารี typecheck build ความสดของชนิดข้อมูล API ชุดทดสอบ และ build Docker image ทุก push'],
    ]),
    ('p',
     'หน้าจอฝั่งผู้ใช้แบ่งตามบทบาท และทุกเส้นทางถูกห่อด้วยสิทธิ์'),
    ('table', [5.0, 5.4, 5.6],
     ['กลุ่มเส้นทาง', 'ตัวอย่าง', 'บทบาทที่เข้าได้'],
     [
        ['สาธารณะ', '/login /register /verify-email /forgot-password /reset-password', 'ทุกคน'],
        ['ผู้ยืม (ฐานร่วมของทุกบทบาท)', '/ /catalog /catalog/:id /rooms /rooms/:id/book /rooms/use /request /pickup /my/loans /my/appeals /profile', 'ผู้ใช้ที่ล็อกอินทุกบทบาท'],
        ['เจ้าหน้าที่', '/staff /staff/handover/:usageKey /staff/inspection /staff/repairs /staff/inventory', 'staff supervisor admin'],
        ['จัดการหน่วยงานและรายงาน', '/staff/users /staff/permissions /staff/settings /reports/analytics /reports/export', 'staff supervisor admin'],
        ['อาจารย์ผู้อนุมัติ', '/supervisor/approvals /supervisor/appeals', 'supervisor admin'],
        ['ผู้ดูแลระบบ', '/admin /admin/users /admin/status /admin/audit /admin/config /admin/reports', 'admin'],
    ]),
    ('h2', '5.2 External Interface'),
    ('table', [4.4, 5.2, 6.4],
     ['ส่วนติดต่อภายนอก', 'ใช้ทำอะไร', 'สถานะ'],
     [
        ['เบราว์เซอร์ของผู้ใช้', 'ช่องทางเข้าใช้งานเดียวของระบบ รองรับ Chrome, Firefox, Safari, Edge', 'ใช้งานแล้ว'],
        ['กล้องบนอุปกรณ์ผู้ใช้', 'ถ่ายรูปหลักฐานตอนรับและตอนคืน ผ่านอินพุตไฟล์ของเบราว์เซอร์', 'ใช้งานแล้ว'],
        ['ที่เก็บไฟล์รูป', 'เก็บรูปบนดิสก์ของเซิร์ฟเวอร์ที่ MEDIA_ROOT รูปสินค้าเปิดได้ทั่วไป รูปหลักฐานเปิดได้เฉพาะผ่านลิงก์ที่เซ็นและหมดอายุ', 'ใช้งานแล้ว'],
        ['บริการส่งอีเมล', 'ยืนยันอีเมล ลืมรหัสผ่าน และเตือนล่วงหน้าก่อนครบกำหนดคืน (FR-NTF-02)', 'ใช้งานแล้วผ่าน SMTP ผู้ให้บริการกำหนดด้วยตัวแปร SMTP_*'],
        ['Google OAuth ของมหาวิทยาลัย', 'ยืนยันตัวตนด้วยบัญชี @ku.th ตาม FR-AUTH-01 และ C-02 ใน SRS v1.1', 'พร้อมใช้งานแต่ปิดไว้ เปิดเมื่อตั้ง GOOGLE_* และจำกัดโดเมนด้วย ALLOWED_EMAIL_DOMAINS'],
    ]),
    ('h2', '5.3 สัญญาระหว่างหน้าเว็บกับเซิร์ฟเวอร์'),
    ('p',
     'สองฝั่งตกลงกันด้วยชนิดข้อมูลของ TypeScript ชุดเดียว การส่งข้อมูลใช้ HTTP/JSON ผ่าน httpBatchLink ที่รวมหลายคำเรียกซึ่งเกิดพร้อมกันให้เป็นคำขอเดียว และแนบคุกกี้ session ไปทุกครั้ง'),
    ('table', [3.8, 5.6, 6.6],
     ['หัวข้อ', 'แบบที่ออกแบบไว้', 'สภาพจริง ณ v1.3'],
     [
        ['เจ้าของสัญญา', 'ฝั่งเซิร์ฟเวอร์สร้างให้อัตโนมัติ', 'backend/scripts/export-api-types.mjs สร้าง frontend/src/server/api-types.d.ts จากเราเตอร์จริง ไฟล์ที่เขียนมือถูกลบแล้ว'],
        ['คำสั่งสร้าง', 'npm run trpc:generate', 'npm run trpc:generate แล้ว npm run api:types'],
        ['ความต่างของสองฝั่ง', 'ไม่มี', 'ไม่มี หน้าเว็บเรียกได้เฉพาะ 111 procedure ที่เซิร์ฟเวอร์มีจริง'],
        ['ตัวจับความต่าง', 'คอมไพล์ไม่ผ่านเมื่อสองฝั่งไม่ตรงกัน', 'ตรงตามแบบ และ CI สร้างไฟล์ใหม่แล้วเทียบกับที่ commit ไว้ ถ้าต่างกัน CI ไม่ผ่าน'],
        ['ผลที่เกิดขึ้นแล้ว', 'ไม่มี', 'ปัญหาหน้ารับของในฉบับ 1.2 แก้แล้ว หน้าจอเรียก image.requestUsagePhotoUpload image.attachUsagePhotos และ loan.confirmMyPickup ที่มีจริง'],
    ]),
    ('h1', '6. Data Store'),
    ('note',
     'ตั้งแต่ migration 20260913000000 คอลัมน์เวลาทุกคอลัมน์ในฐานข้อมูลเป็นชนิด timestamptz(3) ซึ่งเก็บเขตเวลาไว้กับค่าด้วย ค่าเวลาที่บันทึกจากเครื่องคนละเขตเวลา จึงเทียบกันได้ตรง และการคำนวณกำหนดคืนไม่เลื่อนตามเขตเวลาของผู้ใช้'),
    ('h2', '6.1 System Log'),
    ('p',
     'ระบบเก็บบันทึกสามระดับที่มีจุดประสงค์ต่างกัน'),
    ('table', [3.6, 5.4, 7.0],
     ['ชนิดบันทึก', 'เก็บอะไร', 'เก็บที่ไหน'],
     [
        ['Audit Log', 'การกระทำที่เปลี่ยนสิทธิ์หรือข้อมูลสำคัญ และการเข้าสู่ระบบที่สำเร็จ: ใคร ทำอะไร กับอะไร เมื่อไร จากไอพีใด และด้วยเบราว์เซอร์ใด', 'ตาราง AuditLog ในฐานข้อมูล เก็บถาวร ไม่มีฟังก์ชันลบ'],
        ['Cron Run Log', 'ผลการรันงานตามเวลาแต่ละครั้ง', 'ตาราง CronRunLog ในฐานข้อมูล'],
        ['Application Log', 'ข้อผิดพลาดระดับระบบ เหตุการณ์ระหว่างทำงาน และคำขอ HTTP ทุกครั้ง', 'stdout ของคอนเทนเนอร์ อ่านด้วย docker compose logs'],
    ]),
    ('h2', '6.2 Backup Cycle'),
    ('p',
     'ระบบมีข้อมูลสองก้อนที่หายไม่ได้ และทั้งสองก้อนต้องสำรองคู่กันเสมอ'),
    ('table', [3.6, 3.6, 4.0, 4.8],
     ['สิ่งที่สำรอง', 'รอบ', 'เก็บย้อนหลัง', 'วิธี'],
     [
        ['ฐานข้อมูล PostgreSQL', 'ทุกวัน 03:00', '14 วัน', 'บริการ backup ใน docker-compose.prod.yml รัน scripts/backup.sh ด้วย pg_dump เต็มฐาน แล้วคัดลอกไฟล์ออกนอกเครื่อง'],
        ['ไฟล์รูปหลักฐาน (MEDIA_ROOT)', 'ทุกวัน 03:00', '14 วัน', 'บริการ backup เดียวกัน บีบอัดทั้งโฟลเดอร์ทุกรอบ'],
        ['สคีมาและ migration', 'ทุก commit', 'ตลอดอายุโครงการ', 'อยู่ในรีโปอยู่แล้ว ไม่ต้องสำรองแยก'],
        ['ตัวแปรสภาพแวดล้อม', 'เมื่อเปลี่ยน', '—', 'เก็บนอกรีโป ห้าม commit ค่าจริงเข้ารีโปเด็ดขาด'],
    ]),
    ('h1', '7. Security'),
    ('h2', '7.1 User Classification'),
    ('table', [3.6, 5.4, 7.0],
     ['ประเภทผู้ใช้', 'ที่มาของบัญชี', 'ข้อสังเกตด้านความปลอดภัย'],
     [
        ['ผู้ใช้ทั่วไป (นิสิต/บุคลากร)', 'บัญชีในระบบ ผูกกับอีเมลของมหาวิทยาลัย', 'เป็นผู้ใช้ส่วนใหญ่ เข้าถึงได้เฉพาะข้อมูลของตนเองเท่านั้น'],
        ['ผู้ใช้ที่มีอำนาจในหน่วยงาน', 'บัญชีเดียวกัน แต่มีแถวในตาราง Authority', 'เห็นข้อมูลของผู้อื่นได้เฉพาะในหน่วยงานที่ตนมีอำนาจ'],
        ['ผู้ดูแลระบบ', 'กำหนดโดยผู้ดูแลระบบด้วยกัน', 'ไม่ถูกจำกัดขอบเขตหน่วยงาน ทุกการกระทำถูกบันทึกลง Audit Log'],
        ['ผู้ไม่ได้เข้าสู่ระบบ', '—', 'เรียกได้เพียงการเข้าสู่ระบบ สมัคร ยืนยันอีเมล และลืมรหัสผ่าน ทุกทางถูกจำกัดอัตราการเรียก'],
    ]),
    ('h2', '7.2 Role Classification'),
    ('table', [3.0, 4.0, 4.6, 4.4],
     ['บทบาท', 'เก็บที่ไหน', 'ทำอะไรได้เพิ่มจากบทบาทก่อนหน้า', 'ขอบเขต'],
     [
        ['Borrower', 'RoleInfo.RoleName', 'ยืม รับ คืน ต่ออายุ อุทธรณ์ ดูเครดิตของตนเอง', 'เฉพาะข้อมูลของตนเอง'],
        ['Staff', 'RoleInfo.RoleName', 'จัดการบัญชีอุปกรณ์ จ่ายของ รับคืน ตรวจสภาพ บันทึกการซ่อม ตัดสินการต่ออายุที่ต้องตรวจสภาพ', 'เฉพาะหน่วยงานที่ตนมีอำนาจ'],
        ['Supervisor', 'RoleInfo.RoleName', 'อนุมัติคำขอ T2 ตัดสินการต่ออายุ T2 และการอุทธรณ์', 'เฉพาะหน่วยงานที่ตนมีอำนาจ'],
        ['Admin', 'RoleInfo.RoleName', 'จัดการผู้ใช้และบทบาท ตั้งค่าระบบ สั่งงานตามเวลา ดู Audit Log', 'ทั้งระบบ'],
    ]),
    ('h2', '7.3 User and Role Mapping'),
    ('p',
     'ผู้ใช้หนึ่งคนมีบทบาทระดับระบบได้หนึ่งบทบาท และมีอำนาจในหน่วยงานได้หลายหน่วยงานพร้อมกัน'),
    ('table', [4.4, 4.0, 7.6],
     ['ความสัมพันธ์', 'ตาราง', 'ความหมาย'],
     [
        ['ผู้ใช้ → บทบาท', 'AccountInfo.RoleKey → RoleInfo', 'หนึ่งต่อหนึ่ง ตัดสินว่าเรียกฟังก์ชันกลุ่มใดได้'],
        ['ผู้ใช้ → หน่วยงาน', 'Authority (AccountKey + ManageGroupKey)', 'หนึ่งต่อหลาย ตัดสินขอบเขตของข้อมูลที่เห็นและแก้ได้'],
        ['ทรัพยากร → หน่วยงาน', 'ResourceInfo.ManagedBy → ManagementGroup', 'อีกครึ่งหนึ่งของการตัดสินขอบเขต'],
        ['ทรัพยากร → ผู้มีสิทธิ์ยืม', 'Eligibility (ResourceKey + GroupKey + RoleKey)', 'จำกัดว่าใครยืมทรัพยากรชิ้นนั้นได้'],
    ]),
    ('h2', '7.4 Administration Function'),
    ('table', [4.6, 5.4, 6.2],
     ['ฟังก์ชันผู้ดูแลระบบ', 'ทำอะไร', 'สถานะ'],
     [
        ['listUsers getUserById getUserLoans createUser updateUser', 'ค้นหา สร้าง และแก้ไขผู้ใช้ ดูประวัติการยืมของผู้ใช้ (FR-ADM-01)', 'ใช้งานได้จริง'],
        ['changeRole resetPassword', 'เปลี่ยนบทบาทและตั้งรหัสผ่านใหม่ มีผลทันทีในคำขอถัดไป', 'ใช้งานได้จริง'],
        ['setUserActive', 'ปิดและเปิดบัญชี บัญชีที่ถูกปิดใช้งานต่อไม่ได้ทันที setUserBan ตัดออกแล้ว บทลงโทษมีผลผ่านระดับเครดิตเท่านั้นตามแผน', 'ใช้งานได้จริง'],
        ['getLendingSettings updateLendingSettings updateWorkHours', 'ปรับจำนวนวันยืม จำนวนครั้งที่ต่อได้ ช่วงคะแนนเครดิต อัตราหักเครดิต และเวลาทำการ (ค่าเริ่มต้น 08:00-17:00 กำหนดคืนคือเวลาปิด)', 'ใช้งานได้จริง updateWorkHours เฉพาะผู้ดูแลระบบ'],
        ['getConfig', 'ดูค่าตั้งเชิงเทคนิคจากตัวแปรสภาพแวดล้อม', 'ใช้งานได้จริง อ่านอย่างเดียว เปลี่ยนค่าที่การนำขึ้นใช้งาน'],
        ['getSystemStatus listCronJobs runCronJob', 'ดูสถานะระบบ ดูผลงานตามเวลาครั้งล่าสุด และสั่งรันเอง', 'ใช้งานได้จริง ครบ 6 งาน'],
        ['listAudit getAuditById', 'ดู Audit Log และกรองตามผู้กระทำ ชนิดการกระทำ ช่วงเวลา', 'ใช้งานได้จริง'],
    ]),
    ('h1', '8. Authorization'),
    ('p',
     'การควบคุมสิทธิ์ทำสามชั้นซ้อนกัน เส้นทางฝั่งหน้าเว็บตอบว่า “ควรเห็นเมนูนี้ไหม” middleware ฝั่งเซิร์ฟเวอร์ตอบว่า “เรียกฟังก์ชันนี้ได้ไหม” และชั้น service ตอบว่า “จัดการข้อมูลชิ้นนี้ได้ไหม”'),
    ('table', [4.0, 6.4, 5.6],
     ['ตัวกรอง', 'เงื่อนไขที่ต้องผ่าน', 'ถ้าไม่ผ่าน'],
     [
        ['AuthMiddleware', 'ctx.user ต้องไม่เป็น null (มีคุกกี้ที่ยังไม่หมดอายุและยังไม่ถูกเพิกถอน)', 'UNAUTHORIZED — หน้าเว็บพาไปหน้าเข้าสู่ระบบ'],
        ['StaffMiddleware', 'บทบาทเป็น staff supervisor หรือ admin', 'FORBIDDEN'],
        ['SupervisorMiddleware', 'บทบาทเป็น supervisor หรือ admin', 'FORBIDDEN'],
        ['AdminMiddleware', 'บทบาทเป็น admin', 'FORBIDDEN'],
        ['ชั้น service', 'ขอบเขตหน่วยงาน (StaffScopeService) คำขอ T2 ตัดสินได้เฉพาะอาจารย์ ผู้ตัดสินต้องไม่ใช่ผู้ขอ ผู้ตรวจ T2 ต้องไม่ใช่ผู้จัดเตรียม', 'FORBIDDEN พร้อมรหัสเชิงธุรกิจ'],
    ]),
    ('p',
     'การยืนยันตัวตนและการจัดการ session'),
    ('table', [3.8, 6.2, 6.0],
     ['หัวข้อ', 'การออกแบบ', 'เหตุผล'],
     [
        ['การเก็บรหัสผ่าน', 'scrypt พร้อม salt เฉพาะบัญชี เก็บใน AccountInfo.HashedPassword', 'ไม่เก็บรหัสผ่านจริง scrypt ตั้งใจให้ช้าเพื่อกันการเดาสุ่ม'],
        ['รูปแบบ session', 'สุ่มรหัส session แล้วเซ็นด้วย HMAC-SHA256 ตัวโทเค็นไม่พกข้อมูลผู้ใช้เลย', 'ต่อให้อ่านโทเค็นได้ก็ไม่ได้ข้อมูลอะไร และปลอมไม่ได้เพราะไม่มีกุญแจ'],
        ['ที่เก็บฝั่งเซิร์ฟเวอร์', 'ตาราง SessionInfo เก็บค่าแฮช SHA-256 ของรหัส session พร้อมเวลาออก เวลาหมดอายุ และเวลาที่ถูกเพิกถอน', 'ฐานข้อมูลรั่วก็สวมรอยไม่ได้ เพราะค่าที่เก็บไม่ใช่ตัวรหัส'],
        ['การเพิกถอน', 'ออกจากระบบ = ตั้งเวลาเพิกถอน logoutAll ล้างทุก session ของบัญชีเดียวในคำสั่งเดียว (มีปุ่มที่หน้าโปรไฟล์แล้ว)', 'ปิดช่องโหว่ที่โทเค็นแบบไร้สถานะทำไม่ได้ — บัญชีที่ถูกขโมยตัดได้ทันที'],
        ['การตรวจทุกคำขอ', 'ตรวจลายเซ็น หา session ในฐานข้อมูล เช็กการเพิกถอนและวันหมดอายุ แล้วอ่านบัญชีใหม่ทุกครั้ง', 'บทบาทที่เปลี่ยนและบัญชีที่ถูกปิดมีผลทันที ไม่ต้องรอโทเค็นหมดอายุ'],
        ['การกันเดารหัสผ่าน', 'นับความล้มเหลวในหน้าต่าง 15 นาที — เกิน 5 ครั้งต่อบัญชี หรือ 20 ครั้งต่อไอพี แล้วบล็อก 15 นาที', 'ตอบ NFR-SEC-05 สำหรับทางเข้าที่เรียกได้โดยไม่ต้องล็อกอิน'],
        ['CORS', 'อนุญาตเฉพาะ origin ที่ระบุไว้ พร้อม credentials', 'ห้ามใช้เครื่องหมาย * คู่กับ credentials'],
    ]),
    ('p',
     'ความต้องการด้านความปลอดภัยใน SRS กับสิ่งที่การออกแบบนี้ตอบ'),
    ('table', [3.0, 7.2, 5.8],
     ['ข้อกำหนด', 'การออกแบบที่ตอบ', 'สถานะ'],
     [
        ['NFR-SEC-01', 'ให้บริการผ่าน HTTPS ทุกเส้นทาง Caddy ออกใบรับรองด้านหน้า nginx คุกกี้ตั้ง secure อัตโนมัติในโหมด production', 'ตั้งค่าไว้แล้ว รอเครื่องจริง'],
        ['NFR-SEC-02', 'รหัส session อยู่ในคุกกี้ httpOnly ฝั่งเซิร์ฟเวอร์เก็บเพียงค่าแฮช', 'ใช้งานแล้ว'],
        ['NFR-SEC-03', 'ทุกฟังก์ชันประกาศ schema ของข้อมูลเข้า ข้อมูลผิดรูปถูกปฏิเสธก่อนถึงชั้น service', 'ใช้งานแล้ว'],
        ['NFR-SEC-04', 'เข้าถึงฐานข้อมูลผ่าน Prisma เท่านั้น ซึ่งใช้ prepared statement', 'ใช้งานแล้ว'],
        ['NFR-SEC-05', 'จำกัดการเดารหัสผ่านรายบัญชีและรายไอพี จำกัดอัตราทางเข้าที่ไม่ต้องล็อกอิน อ่านไอพีจริงผ่าน TRUST_PROXY_HOPS', 'ใช้งานแล้ว'],
        ['NFR-SEC-06', 'ขอตั๋วอัปโหลดที่เซ็นแล้วและมีอายุ 10 นาที ตรวจชนิดไฟล์จากไบต์จริง ชื่อไฟล์เป็นค่าสุ่ม รูปหลักฐานเปิดได้เฉพาะผ่านลิงก์ที่เซ็นและหมดอายุ', 'ใช้งานแล้ว เก็บบนดิสก์ของเซิร์ฟเวอร์ตาม SRS v1.1'],
        ['FR-AUTH-05', 'จำกัดขอบเขตจากส่วนร่วมของตาราง Authority กับเจ้าของทรัพยากร', 'ใช้งานแล้ว'],
        ['FR-AUTH-07', 'บันทึก Audit Log ของการกระทำที่เปลี่ยนสิทธิ์และข้อมูลสำคัญ', 'ใช้งานแล้ว รวมการเข้าสู่ระบบที่สำเร็จ'],
    ]),
    ('h1', '9. System Recovery Procedure'),
    ('p',
     'ขั้นตอนกู้ระบบเรียงตามความรุนแรงของเหตุ จากเบาไปหนัก ทุกกรณีเริ่มด้วยการหยุดรับคำขอเขียนก่อนเสมอ'),
    ('table', [4.0, 5.6, 6.6],
     ['เหตุการณ์', 'ขั้นตอนกู้', 'เวลาที่ตั้งเป้า'],
     [
        ['บริการล่มแต่ข้อมูลยังดี', 'เริ่มโปรเซสใหม่ ตรวจว่าตัวแปรสภาพแวดล้อมครบ ตรวจการเชื่อมต่อฐานข้อมูล', 'ภายใน 15 นาที'],
        ['ฐานข้อมูลเสียหาย', 'หยุดบริการ กู้จากไฟล์สำรองล่าสุด รัน migration ให้ตรงรุ่นโค้ด ตรวจจำนวนแถวของตารางหลัก เปิดบริการ', 'ภายใน 4 ชั่วโมง ข้อมูลหายไม่เกิน 1 วัน'],
        ['ไฟล์รูปหลักฐานหาย', 'กู้โฟลเดอร์ MEDIA_ROOT จากไฟล์สำรอง ตรวจว่าแถวในตาราง Images ชี้ไปยังไฟล์ที่มีอยู่จริง', 'ภายใน 4 ชั่วโมง'],
        ['งานตามเวลาไม่ทำงาน', 'ดูตาราง CronRunLog หรือหน้า /admin/status หางานที่ล้มเหลว แก้สาเหตุ แล้วสั่งรันเองด้วย admin.runCronJob', 'ภายในรอบถัดไปของงานนั้น'],
        ['สงสัยว่าบัญชีถูกสวมรอย', 'เพิกถอน session ทั้งหมดของบัญชีนั้น ตั้งรหัสผ่านใหม่ ตรวจ Audit Log ย้อนหลัง', 'ทันที'],
        ['กุญแจ SESSION_SECRET รั่ว', 'เปลี่ยนกุญแจแล้วเริ่มบริการใหม่ — session ทุกใบใช้ไม่ได้ทันที ผู้ใช้ทุกคนต้องเข้าสู่ระบบใหม่', 'ทันที'],
    ]),
    ('h1', '10. System Installation and Deployment Procedure'),
    ('h2', '10.1 ตัวแปรสภาพแวดล้อม'),
    ('table', [4.4, 2.4, 3.6, 5.6],
     ['ตัวแปร', 'ฝั่ง', 'ค่าเริ่มต้น', 'ใช้ทำอะไร'],
     [
        ['DATABASE_URL', 'backend', 'ไม่มี — ต้องตั้ง', 'ที่อยู่ของฐานข้อมูล PostgreSQL'],
        ['SESSION_SECRET', 'backend', 'ไม่มี — ต้องตั้ง', 'กุญแจเซ็นรหัส session'],
        ['SESSION_TTL_HOURS', 'backend', '12', 'อายุของ session'],
        ['COOKIE_SECURE', 'backend', 'false', 'บังคับคุกกี้ให้ส่งเฉพาะบน HTTPS (โหมด production เปิดให้เองอยู่แล้ว)'],
        ['COOKIE_SAMESITE', 'backend', 'lax', 'ปรับเมื่อหน้าเว็บกับ API อยู่คนละโดเมน'],
        ['MEDIA_ROOT', 'backend', './media', 'โฟลเดอร์เก็บรูปหลักฐาน'],
        ['PUBLIC_API_URL', 'backend', 'http://localhost:3000', 'ใช้ประกอบ URL ของรูปให้หน้าเว็บเรียกได้'],
        ['PORT', 'backend', '3000', 'พอร์ตที่เซิร์ฟเวอร์ฟัง'],
        ['NODE_ENV', 'backend', 'development', 'ตั้งเป็น production เพื่อเปิด secure cookie'],
        ['CORS_ORIGINS', 'backend', 'http://localhost:5173', 'origin ที่อนุญาต คั่นด้วยจุลภาค'],
        ['SMTP_HOST SMTP_PORT SMTP_SECURE SMTP_USER SMTP_PASS', 'backend', 'localhost 1025 (MailHog)', 'เซิร์ฟเวอร์ส่งอีเมล'],
        ['MAIL_FROM PUBLIC_APP_URL', 'backend', 'ULMs <no-reply@ku.th> / http://localhost:5173', 'ผู้ส่งอีเมล และที่อยู่หน้าเว็บที่ลิงก์ในอีเมลชี้กลับ'],
        ['ADMIN_EMAIL ADMIN_USER_ID ADMIN_PASSWORD ADMIN_FIRST_NAME ADMIN_LAST_NAME', 'backend', 'ไม่มี', 'บัญชีผู้ดูแลคนแรกที่ seed-prod สร้างบนเครื่องจริง'],
        ['GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET GOOGLE_REDIRECT_URI ALLOWED_EMAIL_DOMAINS', 'backend', 'ว่าง = ปิด / ku.th', 'เข้าสู่ระบบด้วยบัญชี Google ของมหาวิทยาลัย'],
        ['TERM_END_DATE', 'backend', 'ว่าง = ปิด', 'วันสิ้นภาคการศึกษา การจองต้องไม่เลยวันนี้'],
        ['TRUST_PROXY_HOPS', 'backend', '2 บนเครื่องจริง', 'จำนวน proxy ข้างหน้า (Caddy และ nginx) เพื่ออ่านไอพีจริงของผู้ใช้'],
        ['DB_POOL_MAX', 'backend', '20', 'จำนวนการเชื่อมต่อฐานข้อมูลสูงสุด ส่วน statement_timeout ตั้งใน DATABASE_URL'],
        ['VITE_TRPC_URL', 'frontend', '/trpc', 'ปลายทางของสัญญา ตอนพัฒนาใช้ dev proxy ของ Vite'],
    ]),
    ('h2', '10.2 ขั้นตอนติดตั้ง'),
    ('code', [
        '# 0 ใช้ Node รุ่นที่ตรึงไว้ใน .nvmrc',
        'nvm use',
        '',
        '# 1 เตรียมฐานข้อมูล',
        'createdb ulms',
        '',
        '# 2 ฝั่งเซิร์ฟเวอร์',
        'cd backend',
        'cp .env.example .env          # แล้วเติม DATABASE_URL และ SESSION_SECRET',
        'npm ci',
        'npx prisma generate',
        'npx prisma migrate deploy     # ใช้ migrate dev เฉพาะตอนพัฒนา',
        'npm run seed                  # ข้อมูลตั้งต้น: ระดับเครดิต บทบาท บัญชีทดสอบ',
        'npm run build && npm run start:prod',
        '',
        '# 3 ฝั่งหน้าเว็บ',
        'cd ../frontend',
        'npm ci',
        'npm run build                 # ได้ไฟล์สแตติกใน dist/ นำไปวางบนเว็บเซิร์ฟเวอร์หรือ CDN',
        '',
        '# 4 เครื่องจริง (รายละเอียดใน docs/deploy.md)',
        'docker compose -f docker-compose.prod.yml up -d --build',
        'docker compose -f docker-compose.prod.yml exec backend node dist/src/seed-prod.js',
    ]),
    ('table', [3.4, 5.4, 7.2],
     ['ขั้น', 'ตรวจอะไรก่อนไปต่อ', 'ถ้าไม่ผ่าน'],
     [
        ['หลังตั้งค่า', 'ตัวแปรที่ไม่มีค่าเริ่มต้นถูกตั้งครบ', 'เซิร์ฟเวอร์จะไม่ยอมเริ่มทำงานและบอกว่าขาดตัวใด'],
        ['หลัง migrate', 'migration ครบ 28 ชุด และมีตาราง 35 ตาราง', 'อย่ารันต่อ ตรวจว่ารุ่นโค้ดกับรุ่น migration ตรงกันไหม'],
        ['หลัง seed', 'มีระดับเครดิตครอบคลุมช่วง 0-100 มีบัญชีครบทุกบทบาท และมี Authority กับ Eligibility ตั้งต้น', 'การยืมจะพังด้วย CREDIT_TIER_NOT_CONFIGURED หรือ TIER_NOT_CONFIGURED'],
        ['หลังเปิดบริการ', 'เรียก auth.login แล้วได้คุกกี้ เรียก auth.me แล้วได้ข้อมูลผู้ใช้ หน้า /admin/status แสดงงานตามเวลาครบ 6 งาน', 'ตรวจ CORS และค่า COOKIE_SAMESITE'],
    ]),
    ('h2', '10.3 การตรวจอัตโนมัติและการทดสอบ'),
    ('table', [4.2, 7.0, 4.8],
     ['งานตรวจ', 'ตรวจอะไร', 'สถานะ'],
     [
        ['CI — รุ่นไลบรารี', 'รุ่นของ zod ที่สองฝั่งใช้ร่วมกันต้องตรงกัน', 'รันทุก pull request เป็นงานบังคับแล้ว'],
        ['CI — ฝั่งเซิร์ฟเวอร์', 'ติดตั้ง typecheck build ความสดของชนิดข้อมูล API migrate และชุดทดสอบ 3 ชุด', 'รันทุก push'],
        ['CI — ฝั่งหน้าเว็บ', 'ติดตั้ง typecheck รันชุดทดสอบ build', 'รันทุก push'],
        ['CI — Docker', 'build image ฝั่งเซิร์ฟเวอร์และหน้าเว็บ', 'รันทุก push'],
        ['ชุดทดสอบหน่วยย่อย', 'service mapper session นโยบายอนุมัติ ต่ออายุ แจ้งเตือน และงานตามเวลา (Jest)', '72 ไฟล์ 615 + 30 + 36 กรณี รันใน CI แล้ว'],
        ['ชุดทดสอบส่วนประกอบหน้าเว็บ', 'หน้าผู้ดูแลระบบ เจ้าหน้าที่ อาจารย์ และผู้ยืม (Vitest)', '21 ไฟล์ 119 กรณี รันใน CI แล้ว'],
        ['ชุดทดสอบผ่านเบราว์เซอร์', 'เส้นทางหลักของทั้ง 4 บทบาท (Playwright)', '10 ไฟล์ 27 กรณี รันก่อนนำขึ้นใช้งาน ยังไม่อยู่ใน CI กรณีที่ต้องมีสล็อตวันนี้ข้ามเองหลังเวลาทำการ'],
        ['ตรวจเกณฑ์การยอมรับฝั่งหน้าเว็บ', 'กฎธุรกิจที่หน้าเว็บคำนวณเอง', '49 ข้อ ผ่านทั้งหมด ยังไม่อยู่ใน CI'],
        ['ตรวจว่าสัญญาสองฝั่งตรงกัน', 'CI สร้าง api-types.d.ts ใหม่แล้วเทียบกับที่ commit', 'ใช้งานแล้ว'],
        ['ทดสอบสมรรถนะ', 'load test ผู้ใช้ 200 คนกับอุปกรณ์ 10,000 ชิ้น เป้าหมาย NFR-PRF (โฟลเดอร์ perf/)', 'ผ่านที่ p95 บนเครื่องพัฒนา ต้องวัดซ้ำบนเครื่องจริง'],
    ]),
    ('h1', '11. Back-out Procedure'),
    ('table', [3.4, 5.6, 7.2],
     ['ขั้น', 'ทำอะไร', 'ข้อควรระวัง'],
     [
        ['1 ตัดสินใจ', 'กำหนดเกณฑ์ล่วงหน้าว่าอาการแบบใดถือว่าต้องถอย เช่น เข้าสู่ระบบไม่ได้ หรือวงจรยืมพัง', 'ตัดสินด้วยเกณฑ์ที่เขียนไว้ก่อน ไม่ใช่ความรู้สึกตอนนั้น'],
        ['2 หยุดรับคำขอเขียน', 'ปิดทางเข้าใช้งานชั่วคราว', 'ถ้าไม่หยุดก่อน ข้อมูลใหม่จะเขียนลงสคีมาที่กำลังจะถอย'],
        ['3 ถอยโค้ด', 'นำรุ่นก่อนหน้ากลับขึ้นใช้งาน ทั้งฝั่งเซิร์ฟเวอร์และไฟล์สแตติกของหน้าเว็บ', 'ต้องถอยพร้อมกันทั้งสองฝั่ง เพราะสัญญาระหว่างกันอาจเปลี่ยนไปแล้ว'],
        ['4 ถอยสคีมา', 'ถ้ารุ่นที่ถอยไปใช้สคีมาเดิม ให้กู้ฐานข้อมูลจากไฟล์สำรองก่อนนำขึ้นใช้งาน', 'migration ที่ลบคอลัมน์ทิ้งจะถอยไม่ได้ ข้อมูลในคอลัมน์นั้นหายถาวร'],
        ['5 ตรวจหลังถอย', 'เข้าสู่ระบบ ดูรายการอุปกรณ์ จ่ายของหนึ่งครั้ง รับคืนหนึ่งครั้ง', 'ถ้าเส้นทางใดไม่ผ่าน อย่าเปิดให้ผู้ใช้เข้าจนกว่าจะแก้เสร็จ'],
        ['6 บันทึก', 'จดว่าอะไรพัง ถอยเพราะอะไร และจะกันไม่ให้เกิดซ้ำอย่างไร', 'ลงใน PROGRESS ของโครงการ'],
    ]),
    ('p',
     'กฎการเขียน migration ให้ถอยได้ ใช้กับทุก migration'),
    ('bullets', [
        'เพิ่มคอลัมน์ใหม่ให้เป็นค่าว่างได้ หรือมีค่าเริ่มต้นเสมอ — รุ่นเก่าที่ไม่รู้จักคอลัมน์นั้นจะยังทำงานได้ (ExtensionRequest.Reason ทำตามข้อนี้)',
        'แยกการเพิ่มกับการลบออกจากกันคนละรอบ: รอบนี้เพิ่มของใหม่และเขียนสองที่ รอบหน้าค่อยลบของเก่า',
        'อย่าเปลี่ยนความหมายของคอลัมน์เดิม ให้เพิ่มคอลัมน์ใหม่แทน',
        'สำรองฐานข้อมูลก่อนรัน migration ที่ลบหรือแก้โครงสร้างทุกครั้ง',
    ]),
    ('h1', 'ภาคผนวก ก: สถานะการพัฒนา ณ วันจัดทำเอกสาร'),
    ('p',
     'นับจาก front-end-branch วันที่ 25 ก.ย. 2569'),
    ('table', [5.4, 3.4, 7.2],
     ['ส่วนของระบบ', 'สถานะ', 'หมายเหตุ'],
     [
        ['เข้าสู่ระบบ ออกจากระบบ ออกจากระบบทุกเครื่อง', 'ใช้งานได้จริง', 'session เก็บในฐานข้อมูล เพิกถอนได้ จำกัดการเดารหัสผ่านแล้ว บันทึก Audit Log ตอนเข้าสู่ระบบ'],
        ['ฟังก์ชันฝั่งผู้ดูแลระบบ (admin 18)', 'ใช้งานได้จริง 18 จาก 18', 'รวมประวัติการยืมของผู้ใช้ เวลาทำการ และการสั่งงานตามเวลา'],
        ['บัญชีอุปกรณ์และสถานที่ (item 29)', 'ใช้งานได้จริง', 'รวมสิทธิ์การเข้าใช้ ของคงเหลือ ช่วงเวลาว่างของห้อง และการปลดระวาง'],
        ['วงจรยืม-คืนฝั่งเซิร์ฟเวอร์ (loan 20 approval 7 inspection 9 appeal 6)', 'ใช้งานได้จริง', 'ส่งคำขอ จองห้อง อนุมัติ จ่ายของ เปลี่ยนชิ้น รับคืน แจ้งของหาย ตรวจสภาพ ซ่อม ต่ออายุ อุทธรณ์'],
        ['หน้าจอเจ้าหน้าที่และอาจารย์', 'ใช้งานได้จริง', 'คิวงาน ส่งมอบ คลังอุปกรณ์ ตรวจสภาพ ซ่อม ตั้งค่าการยืม ผู้ใช้ สิทธิ์ อนุมัติ อุทธรณ์ เรียกเซิร์ฟเวอร์จริงทั้งหมด'],
        ['หน้าจอผู้ยืม', 'ใช้งานได้จริง', 'ส่งคำขอ จองห้อง รับของ ต่ออายุ อุทธรณ์ และดูเครดิต ผ่านเซิร์ฟเวอร์ทั้งหมด'],
        ['การแจ้งเตือน (notification 4)', 'ใช้งานได้จริง', 'ในระบบและอีเมล มีกุญแจกันแจ้งซ้ำ เจ้าหน้าที่ได้รับแจ้งเมื่อมีของต้องเตรียม รอรับคืน หรือห้องต้องตรวจ'],
        ['งานตามเวลา', 'ใช้งานได้จริง 6 จาก 6', 'สองงานที่ไม่จำเป็นตัดออกแล้ว ดูหัวข้อ 4.2.2'],
        ['รายงาน (report 1)', 'ใช้งานได้จริง', 'สรุปรายหน่วยงาน สถิติความเสียหาย การใช้ห้อง และการส่งออก'],
        ['อัปโหลดรูปหลักฐาน (image 5)', 'ใช้งานได้จริง', 'เก็บลงดิสก์ที่ MEDIA_ROOT รูปหลักฐานเปิดผ่านลิงก์ที่เซ็นและหมดอายุ'],
        ['สมรรถนะ (NFR-PRF)', 'ผ่านบนเครื่องพัฒนา', 'อุปกรณ์ 10,000 ชิ้น ผู้ใช้ 200 คน p95 อยู่ในเป้า ต้องวัดซ้ำบนเครื่องจริง'],
        ['เข้าสู่ระบบด้วยบัญชีของมหาวิทยาลัย', 'พร้อมแต่ปิดไว้', 'เปิดได้ด้วยตัวแปร GOOGLE_* ทางหลักคือบัญชีในระบบที่ยืนยันอีเมล @ku.th (SRS v1.1)'],
        ['สัญญาระหว่างสองฝั่ง', 'ตรงกัน', 'สร้างอัตโนมัติและตรวจใน CI ดูหัวข้อ 5.3'],
        ['ชุดทดสอบอัตโนมัติ', 'ใช้งานได้จริง', 'ฝั่งเซิร์ฟเวอร์ 681 กรณี หน้าเว็บ 119 กรณี ผ่านเบราว์เซอร์ 27 กรณี ชุดผ่านเบราว์เซอร์ยังไม่อยู่ใน CI'],
        ['การนำขึ้นใช้งาน', 'เตรียมพร้อม ยังไม่นำขึ้น', 'Docker Compose สำรองข้อมูลทุกวัน 03:00 ดู docs/deploy.md'],
        ['FR-APV-01 ประวัติผู้ยืมในคิวอนุมัติ', 'เลื่อนออกไป', 'ตามที่ทีมตัดสิน บันทึกไว้ใน SRS v1.1 หัวข้อ 3.7'],
        ['คำแปลข้อความผิดพลาด', 'ขาด 1 ตัว', '103 จาก 104 รหัสมีคำแปลไทย ดูหัวข้อ 4.2.2'],
        ['การต่ออายุเทียบ SRS', 'ต้องตัดสิน 1 ข้อ', 'D2-D3 ส่งอาจารย์แล้ว เหลือ T3 ที่ส่งเจ้าหน้าที่ ขณะที่ FR-RNW-04 เขียนต่างไป ดูหัวข้อ 2.3.2'],
    ]),
]
